G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -8 ],
        [ RationalField() | 5 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -56 ],
        [ RationalField() | 133 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 8 ],
        [ RationalField() | 5 ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -5, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 14, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 3, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -56, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 133, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | 3 ],
    [ RationalField() | 35 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -5, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 14, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 3, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -56, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 133, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -5, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 14, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 3, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -56, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 133, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 56 ],
        [ RationalField() | 133 ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(CyclotomicField(1320)) |
    [ CyclotomicField(1320) |
        [ RationalField() | 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(1320) |
        [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 3, 2, 0, 2, 0, 0, 0, -2, 0, 0, 0, 2, 0, 0, 0, 
            -2, 0, 0, 0, 2, 0, 0, 0, -2, 0, 0, 0, 2, 0, 0, 0, -2, 0, 0, 0, 2, 0,
            0, 0, -2 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 4, 4, 2, 4, 0, 0, -1, -4, 0, 0, 1, 4, 0, 0, -1, 
            -4, 0, 0, 1, 4, 0, 0, -1, -4, 0, 0, 1, 4, 0, 0, -1, -4, 0, 0, 1, 4, 
            0, 0, -1, -4 ]
        ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 14, 6, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, 
            -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0,
            0, 0, -6 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 22, 14, 2, 14, 0, 0, -1, -14, 0, 0, 1, 14, 0, 0,
            -1, -14, 0, 0, 1, 14, 0, 0, -1, -14, 0, 0, 1, 14, 0, 0, -1, -14, 0, 
            0, 1, 14, 0, 0, -1, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 8, 8, 2, 8, 0, 0, -1, -8, 0, 0, 1, 8, 0, 0, -1, 
            -8, 0, 0, 1, 8, 0, 0, -1, -8, 0, 0, 1, 8, 0, 0, -1, -8, 0, 0, 1, 8, 
            0, 0, -1, -8 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 22, 8, 14, 8, 0, 0, -7, -8, 0, 0, 7, 8, 0, 0, 
            -7, -8, 0, 0, 7, 8, 0, 0, -7, -8, 0, 0, 7, 8, 0, 0, -7, -8, 0, 0, 7,
            8, 0, 0, -7, -8 ]
        ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 15, 6, 0, 6, 0, -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 
            0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 36, 20, 0, 20, 0, -20, 1, 0, 0, 20, 0, 0, 0, 
            -20, 0, 0, 0, 20, 0, 0, 0, -20, 0, 0, 0, 20, 0, 0, 0, -20, 0, 0, 0, 
            20, 0, 0, 0, -20, -1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 9, 8, 0, 8, 0, -8, 1, 0, 0, 8, 0, 0, 0, -8, 0, 
            0, 0, 8, 0, 0, 0, -8, 0, 0, 0, 8, 0, 0, 0, -8, 0, 0, 0, 8, 0, 0, 0, 
            -8, -1, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 30, 16, 0, 16, 0, -16, 8, 0, 0, 16, 0, 0, 0, 
            -16, 0, 0, 0, 16, 0, 0, 0, -16, 0, 0, 0, 16, 0, 0, 0, -16, 0, 0, 0, 
            16, 0, 0, 0, -16, -8, 0 ]
        ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 22, 0, 32, 0, 0, 0, -16, 0, 2, 0, 16, 0, -2, 0, 
            -16, 0, 2, 0, 16, 0, -2, 0, -16, 0, 2, 0, 16, 0, -2, 0, -16, 0, 2, 
            0, 16, 0, -2, 0, -16, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 59, 0, 64, 0, 0, 0, -32, 0, 10, 0, 32, 0, -10, 
            0, -32, 0, 10, 0, 32, 0, -10, 0, -32, 0, 10, 0, 32, 0, -10, 0, -32, 
            0, 10, 0, 32, 0, -10, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 0, 0, 54, 0, 0, 0, -26, 0, 0, 0, 27, 0, 0, 0, 
            -27, 0, 0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 
            27, 0, 0, 0, -28, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 106, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, -27, 0, 
            0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 27, 0, 
            0, 0, -27, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 32, 0, 24, 0, 0, 0, -12, 0, 0, 0, 12, 0, 0, 0, 
            -12, 0, 0, 0, 12, 0, 0, 0, -12, 0, 0, 0, 12, 0, 0, 0, -12, 0, 0, 0, 
            12, 0, 0, 0, -12, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 68, 0, 64, 0, 0, 0, -32, 0, 1, 0, 32, 0, -1, 0, 
            -32, 0, 1, 0, 32, 0, -1, 0, -32, 0, 1, 0, 32, 0, -1, 0, -32, 0, 1, 
            0, 32, 0, -1, 0, -32, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(CyclotomicField(88)) |
    [ CyclotomicField(88) |
        [ RationalField() | 92, 64, 28, 64, 0, 0, -14, -64, 0, 0, 14, 64, 0, 0, 
        -14, -64, 0, 0, 14, 64, 0, 0, -14, -64, 0, 0, 14, 64, 0, 0, -14, -64, 0,
        0, 14, 64, 0, 0, -14, -64 ]
    ],
    [ CyclotomicField(88) |
        [ RationalField() | 134, 56, 2, 56, 0, 0, -1, -56, 0, 0, 1, 56, 0, 0, 
        -1, -56, 0, 0, 1, 56, 0, 0, -1, -56, 0, 0, 1, 56, 0, 0, -1, -56, 0, 0, 
        1, 56, 0, 0, -1, -56 ]
    ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | -6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | -5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(CyclotomicField(88)) |
    [ CyclotomicField(88) |
        [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(88) |
        [ RationalField() | 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 56 ],
        [ RationalField() | 133 ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 56 ],
        [ RationalField() | 133 ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 56 ],
        [ RationalField() | 133 ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 34, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -56, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 133, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
