G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 9, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 15, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 0, 9 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 15, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -27, -27 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 78, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 0, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 6, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -9, -9 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 15, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 0, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -3, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 0, 27 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 78, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 9, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -27, 0, 0, -27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -9, 0, 0, -9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -13, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 50, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 572, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 9, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -9, 0, 0, -9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -27, 0, 0, -27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 9, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -9, 0, 0, -9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -27, 0, 0, -27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(1320))) |
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | -7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(1320)) |
        [ CyclotomicField(1320) |
            [ RationalField() | 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(1320) |
            [ RationalField() | 34, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(1320)) |
    [ CyclotomicField(1320) |
        [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(1320) |
        [ RationalField() | -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(1320) |
        [ RationalField() | 77, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(1320) |
        [ RationalField() | 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 3, 2, 0, 2, 0, 0, 0, -2, 0, 0, 0, 2, 0, 0, 0, 
            -2, 0, 0, 0, 2, 0, 0, 0, -2, 0, 0, 0, 2, 0, 0, 0, -2, 0, 0, 0, 2, 0,
            0, 0, -2 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 4, 4, 2, 4, 0, 0, -1, -4, 0, 0, 1, 4, 0, 0, -1, 
            -4, 0, 0, 1, 4, 0, 0, -1, -4, 0, 0, 1, 4, 0, 0, -1, -4, 0, 0, 1, 4, 
            0, 0, -1, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 1, 2, 2, 2, 0, 0, -1, -2, 0, 0, 1, 2, 0, 0, -1, 
            -2, 0, 0, 1, 2, 0, 0, -1, -2, 0, 0, 1, 2, 0, 0, -1, -2, 0, 0, 1, 2, 
            0, 0, -1, -2 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 4, 4, 2, 4, 0, -2, -1, -2, 0, 2, 1, 2, 0, -2, 
            -1, -2, 0, 2, 1, 2, 0, -2, -1, -2, 0, 2, 1, 2, 0, -2, -1, -2, 0, 2, 
            1, 2, 0, -2, -1, -2 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 14, 6, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, 
            -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0,
            0, 0, -6 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 22, 14, 2, 14, 0, 0, -1, -14, 0, 0, 1, 14, 0, 0,
            -1, -14, 0, 0, 1, 14, 0, 0, -1, -14, 0, 0, 1, 14, 0, 0, -1, -14, 0, 
            0, 1, 14, 0, 0, -1, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 8, 8, 2, 8, 0, 0, -1, -8, 0, 0, 1, 8, 0, 0, -1, 
            -8, 0, 0, 1, 8, 0, 0, -1, -8, 0, 0, 1, 8, 0, 0, -1, -8, 0, 0, 1, 8, 
            0, 0, -1, -8 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 22, 8, 14, 8, 0, 0, -7, -8, 0, 0, 7, 8, 0, 0, 
            -7, -8, 0, 0, 7, 8, 0, 0, -7, -8, 0, 0, 7, 8, 0, 0, -7, -8, 0, 0, 7,
            8, 0, 0, -7, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 8, 6, 6, 6, 0, 0, -3, -6, 0, 0, 3, 6, 0, 0, -3, 
            -6, 0, 0, 3, 6, 0, 0, -3, -6, 0, 0, 3, 6, 0, 0, -3, -6, 0, 0, 3, 6, 
            0, 0, -3, -6 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 12, 14, 12, 14, 0, -2, -6, -12, 0, 2, 6, 12, 0, 
            -2, -6, -12, 0, 2, 6, 12, 0, -2, -6, -12, 0, 2, 6, 12, 0, -2, -6, 
            -12, 0, 2, 6, 12, 0, -2, -6, -12 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 5, 10, 0, 5, 0, -10, 5, 0, 0, 10, 0, 0, 0, -10, 
            0, 0, 0, 10, 0, 0, 0, -10, 0, 0, 0, 10, 0, 0, 0, -10, 0, 0, 0, 10, 
            0, -1, 0, -10, -1, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 26, 11, 0, 11, 0, -11, 10, 0, 0, 16, 0, 0, 0, 
            -11, 0, 0, 0, 11, 0, 0, 0, -11, 0, 0, 0, 11, 0, 0, 0, -11, 0, 0, 0, 
            11, 0, -5, 0, -11, -10, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 15, 6, 0, 6, 0, -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 
            0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 36, 20, 0, 20, 0, -20, 1, 0, 0, 20, 0, 0, 0, 
            -20, 0, 0, 0, 20, 0, 0, 0, -20, 0, 0, 0, 20, 0, 0, 0, -20, 0, 0, 0, 
            20, 0, 0, 0, -20, -1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 9, 6, 0, 6, 0, -6, 3, 0, 0, 6, 0, 0, 0, -6, 0, 
            0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, -6, 0, 0, 0, 6, 0, 0, 0, 
            -6, -3, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 20, 18, 0, 18, 0, -18, 9, 0, 0, 20, 0, 0, 0, 
            -18, 0, 0, 0, 18, 0, 0, 0, -18, 0, 0, 0, 18, 0, 0, 0, -18, 0, 0, 0, 
            18, 0, -2, 0, -18, -9, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 9, 8, 0, 8, 0, -8, 1, 0, 0, 8, 0, 0, 0, -8, 0, 
            0, 0, 8, 0, 0, 0, -8, 0, 0, 0, 8, 0, 0, 0, -8, 0, 0, 0, 8, 0, 0, 0, 
            -8, -1, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 30, 16, 0, 16, 0, -16, 8, 0, 0, 16, 0, 0, 0, 
            -16, 0, 0, 0, 16, 0, 0, 0, -16, 0, 0, 0, 16, 0, 0, 0, -16, 0, 0, 0, 
            16, 0, 0, 0, -16, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 0, 16, 0, 0, 0, -16, 10, 0, 0, 16, 0, 0, 0, -16,
            0, 0, 0, 16, 0, 0, 0, -16, 0, 0, 0, 16, 0, 0, 0, -16, 0, 0, -1, 16, 
            0, 0, 0, -16, 0, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 46, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -16, 0, 
            0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 5, 5, 0, 10, 0, -5, 1, 0, 0, 6, 0, 0, 0, -5, 0, 
            0, 0, 5, 0, 0, 0, -5, 0, 0, 0, 5, 0, 0, 0, -5, 0, 0, 0, 5, 0, 0, 0, 
            -5, -5, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 26, 11, 0, 11, 0, -11, 10, 0, 0, 16, 0, 0, 0, 
            -11, 0, 0, 0, 11, 0, 0, 0, -11, 0, 0, 0, 11, 0, 0, 0, -11, 0, 0, 0, 
            11, 0, -5, 0, -11, -10, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            -10, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 46, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -16, 0, 
            0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 22, 0, 32, 0, 0, 0, -16, 0, 2, 0, 16, 0, -2, 0, 
            -16, 0, 2, 0, 16, 0, -2, 0, -16, 0, 2, 0, 16, 0, -2, 0, -16, 0, 2, 
            0, 16, 0, -2, 0, -16, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 59, 0, 64, 0, 0, 0, -32, 0, 10, 0, 32, 0, -10, 
            0, -32, 0, 10, 0, 32, 0, -10, 0, -32, 0, 10, 0, 32, 0, -10, 0, -32, 
            0, 10, 0, 32, 0, -10, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 18, 0, 30, 0, 0, 0, -14, 0, 6, 0, 15, 0, -6, 0, 
            -15, 0, 6, 0, 15, 0, -6, 0, -15, 0, 6, 0, 15, 0, -6, 0, -15, 0, 6, 
            0, 15, 0, -6, 0, -16, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 53, 0, 52, 0, 0, 0, -20, 0, 16, 0, 26, 0, -16, 
            0, -26, 0, 16, 0, 26, 0, -16, 0, -26, 0, 16, 0, 26, 0, -16, 0, -26, 
            0, 16, 0, 26, 0, -16, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 0, 0, 54, 0, 0, 0, -26, 0, 0, 0, 27, 0, 0, 0, 
            -27, 0, 0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 
            27, 0, 0, 0, -28, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 106, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, -27, 0, 
            0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 27, 0, 0, 0, -27, 0, 0, 0, 27, 0, 
            0, 0, -27, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 26, 0, 24, 0, 0, 0, -12, 0, 6, 0, 12, 0, -6, 0, 
            -12, 0, 6, 0, 12, 0, -6, 0, -12, 0, 6, 0, 12, 0, -6, 0, -12, 0, 6, 
            0, 12, 0, -6, 0, -12, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 54, 0, 60, 0, 0, 0, -28, 0, 15, 0, 30, 0, -15, 
            0, -30, 0, 15, 0, 30, 0, -15, 0, -30, 0, 15, 0, 30, 0, -15, 0, -30, 
            0, 15, 0, 30, 0, -15, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 32, 0, 24, 0, 0, 0, -12, 0, 0, 0, 12, 0, 0, 0, 
            -12, 0, 0, 0, 12, 0, 0, 0, -12, 0, 0, 0, 12, 0, 0, 0, -12, 0, 0, 0, 
            12, 0, 0, 0, -12, 0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 68, 0, 64, 0, 0, 0, -32, 0, 1, 0, 32, 0, -1, 0, 
            -32, 0, 1, 0, 32, 0, -1, 0, -32, 0, 1, 0, 32, 0, -1, 0, -32, 0, 1, 
            0, 32, 0, -1, 0, -32, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(88)) |
    [ CyclotomicField(88) |
        [ RationalField() | 92, 64, 28, 64, 0, 0, -14, -64, 0, 0, 14, 64, 0, 0, 
        -14, -64, 0, 0, 14, 64, 0, 0, -14, -64, 0, 0, 14, 64, 0, 0, -14, -64, 0,
        0, 14, 64, 0, 0, -14, -64 ]
    ],
    [ CyclotomicField(88) |
        [ RationalField() | 134, 56, 2, 56, 0, 0, -1, -56, 0, 0, 1, 56, 0, 0, 
        -1, -56, 0, 0, 1, 56, 0, 0, -1, -56, 0, 0, 1, 56, 0, 0, -1, -56, 0, 0, 
        1, 56, 0, 0, -1, -56 ]
    ],
    [ CyclotomicField(88) |
        [ RationalField() | 82, 56, 54, 56, 0, -2, -27, -54, 0, 2, 27, 54, 0, 
        -2, -27, -54, 0, 2, 27, 54, 0, -2, -27, -54, 0, 2, 27, 54, 0, -2, -27, 
        -54, 0, 2, 27, 54, 0, -2, -27, -54 ]
    ],
    [ CyclotomicField(88) |
        [ RationalField() | 64, 64, 56, 64, 0, -8, -28, -56, 0, 8, 28, 56, 0, 
        -8, -28, -56, 0, 8, 28, 56, 0, -8, -28, -56, 0, 8, 28, 56, 0, -8, -28, 
        -56, 0, 8, 28, 56, 0, -8, -28, -56 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(88))) |
    [ PowerSequence(CyclotomicField(88)) |
        [ CyclotomicField(88) |
            [ RationalField() | 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0 ]
        ],
        [ CyclotomicField(88) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(88)) |
    [ CyclotomicField(88) |
        [ RationalField() | 248, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 27, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 78, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 27, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 78, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 27, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 78, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 9, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -9, 0, 0, -9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -27, 0, 0, -27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 9, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -27, 0, 0, -27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -9, 0, 0, -9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
