G2_ELTS6 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -1, 0 ],
            [ RationalField() | 1, 0 ],
            [ RationalField() | 5, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -1, 0 ],
            [ RationalField() | 1, 0 ],
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | 1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -1, 0 ],
            [ RationalField() | -2, 0 ],
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 5, 0 ],
            [ RationalField() | 1, 0 ]
        ]
    ]
}
;
F4_ELTS6 := 
{ PowerSequence(PowerSequence(CyclotomicField(6))) |
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -6, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | -3, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | 8, 0 ],
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | 35, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -6, 0 ],
            [ RationalField() | 8, 0 ],
            [ RationalField() | 0, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | -1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | -1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | -2, 0 ],
            [ RationalField() | 2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -6, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | 3, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ],
            [ RationalField() | -2, 0 ],
            [ RationalField() | 2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | 11, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | -2, 0 ],
            [ RationalField() | 14, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | 5, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | 8, 0 ],
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | -1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | 8, 0 ],
            [ RationalField() | -4, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | 11, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(6)) |
        [ CyclotomicField(6) |
            [ RationalField() | -6, 0 ],
            [ RationalField() | -1, 0 ],
            [ RationalField() | 15, 0 ]
        ],
        [ CyclotomicField(6) |
            [ RationalField() | 20, 0 ],
            [ RationalField() | 7, 0 ],
            [ RationalField() | 23, 0 ]
        ]
    ]
}
;
E6_ELTS6 := 
{ PowerSequence(PowerSequence(CyclotomicField(18))) |
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -27, 0, 0 ],
            [ RationalField() | 5, 0, 0, -5, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 78, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | -27, 0, 0, 27, 0, 0 ],
            [ RationalField() | 0, 0, 0, -3, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 78, 0, 0, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 2, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, -8, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, -2, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | -9, 0, 0, 9, 0, 0 ],
            [ RationalField() | 0, 0, 0, -1, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -9, 0, 0 ],
            [ RationalField() | 3, 0, 0, -3, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0 ],
            [ RationalField() | -9, 0, 0, 8, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -16, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 38, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -9, 0, 0 ],
            [ RationalField() | -1, 0, 0, 1, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -9, 0, 0 ],
            [ RationalField() | 9, 0, 0, -1, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -12, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | -9, 0, 0, 9, 0, 0 ],
            [ RationalField() | 0, 0, 0, -21, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 55, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -9, 0, 0 ],
            [ RationalField() | -3, 0, 0, 3, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -27, 0, 0 ],
            [ RationalField() | -3, 0, 0, 3, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 78, 0, 0, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | -9, 0, 0, 9, 0, 0 ],
            [ RationalField() | -8, 0, 0, 9, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 38, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0 ],
            [ RationalField() | 21, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 55, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 16, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 38, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | -9, 0, 0, 9, 0, 0 ],
            [ RationalField() | 0, 0, 0, -3, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -4, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 4, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -6, 0, 0, 6, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | -27, 0, 0, 27, 0, 0 ],
            [ RationalField() | 0, 0, 0, 5, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 78, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | -9, 0, 0, 9, 0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -9, 0, 0 ],
            [ RationalField() | 1, 0, 0, -9, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 12, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -12, 0, 0, 12, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | -5, 0, 0, 0, 0, 0 ],
            [ RationalField() | -9, 0, 0, 9, 0, 0 ],
            [ RationalField() | 8, 0, 0, 1, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -9, 0, 0 ],
            [ RationalField() | -21, 0, 0, 21, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0 ],
            [ RationalField() | 55, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(18)) |
        [ CyclotomicField(18) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, -6, 0, 0 ]
        ],
        [ CyclotomicField(18) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS6 := 
{ PowerSequence(PowerSequence(CyclotomicField(12))) |
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -56, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 133, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -10, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ],
            [ RationalField() | -19, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 35, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -34, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 71, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 11, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -56, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | -20, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 133, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 71, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | -44, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 98, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | -25, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 52, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 23, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -56, 0, 0, 0 ],
            [ RationalField() | -25, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 133, 0, 0, 0 ],
            [ RationalField() | 52, 0, 0, 0 ],
            [ RationalField() | 52, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -56, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 133, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 26, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 50, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | -25, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 52, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -25, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 52, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ],
            [ RationalField() | 19, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 35, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ],
            [ RationalField() | -5, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 11, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 44, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 98, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -14, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 23, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -26, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 50, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | -56, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 133, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(12)) |
        [ CyclotomicField(12) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -25, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ]
        ],
        [ CyclotomicField(12) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 52, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ]
        ]
    ]
}
;
E8_ELTS6 := 
{ PowerSequence(CyclotomicField(6)) |
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 5, 0 ],
        [ RationalField() | 1, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 14, 0 ],
        [ RationalField() | 16, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 14, 0 ],
        [ RationalField() | 142, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | -4, 0 ],
        [ RationalField() | 4, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 77, 0 ],
        [ RationalField() | 13, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | -4, 0 ],
        [ RationalField() | 76, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 5, 0 ],
        [ RationalField() | 37, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 77, 0 ],
        [ RationalField() | -3, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 77, 0 ],
        [ RationalField() | 189, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | -4, 0 ],
        [ RationalField() | 24, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | -4, 0 ],
        [ RationalField() | 0, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 5, 0 ],
        [ RationalField() | 105, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 14, 0 ],
        [ RationalField() | 54, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 77, 0 ],
        [ RationalField() | -5, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 14, 0 ],
        [ RationalField() | -2, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 14, 0 ],
        [ RationalField() | 0, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 77, 0 ],
        [ RationalField() | 27, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 5, 0 ],
        [ RationalField() | 9, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 14, 0 ],
        [ RationalField() | 6, 0 ]
    ],
    [ CyclotomicField(6) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 5, 0 ],
        [ RationalField() | -3, 0 ]
    ]
}
;
