G2_ELTS8 := 
{ PowerSequence(PowerSequence(CyclotomicField(8))) |
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 1, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 1, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ]
    ]
}
;
F4_ELTS8 := 
{ PowerSequence(PowerSequence(CyclotomicField(8))) |
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, -6, 0, 6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 12, -10, 0, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 6, -6, 0, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ],
            [ RationalField() | 2, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 6, -4, 0, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ],
            [ RationalField() | 10, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ],
            [ RationalField() | 2, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 4, -4, 0, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 6, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 0, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 4, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 4, 4, 0, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 6, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 6, 4, 0, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ],
            [ RationalField() | 10, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, 6, 0, -6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 12, 10, 0, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 0, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 4, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 8, 8, 0, -8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 22, 8, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 8, -8, 0, 8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 22, -8, 0, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 6, 6, 0, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 6, 0, -6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 22, 14, 0, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, -6, 0, 6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -4, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 22, -14, 0, 14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -6, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 20, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0 ]
        ]
    ]
}
;
E6_ELTS8 := 
{ PowerSequence(PowerSequence(CyclotomicField(8))) |
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | 1, 0, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 1, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -3, 4, 0, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0 ],
            [ RationalField() | 15, -6, 0, 6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 36, -20, 0, 20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 3, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, -16, 0 ],
            [ RationalField() | 1, 0, 0, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 6, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | -1, -2, -2, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 4, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | -5, 10, -10, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 28, -20, 0, 20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -5, -2, 8, -6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 20, -12, 0, 12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -3, -2, 4, -6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 12, -8, 0, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -5, 2, 8, 6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 20, 12, 0, -12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | 3, -4, -2, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, -16, 0 ],
            [ RationalField() | -1, 0, 2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | 5, 4, 4, -10 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, 6, 0, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 8, -6, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, -8, 0, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | -5, -4, 6, -10 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, -14, 0, 14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, -16, 0 ],
            [ RationalField() | -1, 0, -6, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | 3, -6, -2, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 12, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | -3, 4, -4, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, -6, 0, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, 16, 0 ],
            [ RationalField() | -1, 0, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0 ],
            [ RationalField() | 15, 6, 0, -6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 36, 20, 0, -20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 6, 8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 8, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | -1, -2, 2, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 4, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0 ],
            [ RationalField() | -1, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 4, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | 1, 0, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | -1, 2, 2, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 4, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 9, -6, 0, 6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 20, -16, 0, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, 16, 0 ],
            [ RationalField() | 1, 4, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 6, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | -1, 2, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -5, -6, -8, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 20, 12, 0, -12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0 ],
            [ RationalField() | -5, -4, 0, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, 16, 0 ],
            [ RationalField() | -1, 16, -10, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 46, -16, 0, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | 1, -2, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | -1, 0, 2, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, 0, 2, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | 3, -2, 2, 6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 12, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 1, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | -5, -2, 10, -10 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 28, -20, 0, 20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | -5, -10, -6, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, 14, 0, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -3, -4, 0, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0 ],
            [ RationalField() | -5, 4, 0, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, 4, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | -5, 4, 6, 10 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, 14, 0, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | -1, 0, 2, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | -1, 0, 2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -7, 8, 0, 8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 30, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | 3, 2, 2, -6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 12, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | -5, 10, -6, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, -14, 0, 14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | 5, -10, -4, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, -6, 0, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -3, 6, -4, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 12, -8, 0, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 9, 6, 0, -6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 20, 16, 0, -16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, -2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 5, 4, 0, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 10, 8, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | 3, -2, 2, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, -2, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 3, -2, 0, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 4, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | -1, 2, -2, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 4, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 9, -8, 0, 8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 30, -16, 0, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | 3, 0, 2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 0, 6, -8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, -8, 0, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | 5, 10, -4, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, 6, 0, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 7, 4, 0, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 16, 8, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, 16, 0 ],
            [ RationalField() | -1, 0, 6, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | -3, -4, -4, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, 6, 0, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -5, 6, -8, 2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 20, -12, 0, 12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | -5, 0, 10, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 24, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -3, 0, -4, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 5, -4, 0, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 10, -8, 0, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, -16, 0 ],
            [ RationalField() | 1, 0, 0, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 6, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | -5, 0, -10, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 24, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | 5, -4, 4, 10 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 26, -6, 0, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, -4, -4, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | -1, 0, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, -8, -6, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 8, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | 3, 0, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -3, 2, 4, 6 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 12, 8, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, 16, 0 ],
            [ RationalField() | 1, -4, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 6, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, -8, 0 ],
            [ RationalField() | -5, 2, 10, 10 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 28, 20, 0, -20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, 0, 2, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | 1, 2, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | -1, -2, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 2, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | -3, 2, 4, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, 6, 0, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -3, -6, -4, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 12, 8, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -3, 0, 4, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -7, -8, 0, -8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 30, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, -16, 0 ],
            [ RationalField() | -1, 0, 10, 16 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 46, 16, 0, -16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, -16, 0 ],
            [ RationalField() | -1, 0, 10, -16 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 46, -16, 0, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | 3, 2, 2, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -9, 0, 16, 0 ],
            [ RationalField() | -1, -16, -10, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 46, 0, 0, 0 ],
            [ RationalField() | 46, 16, 0, -16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | 7, -4, 0, 4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 16, -8, 0, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | 3, 6, -2, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 12, 4, 0, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, 4, 0 ],
            [ RationalField() | -3, -2, 4, -4 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, -6, 0, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -5, 0, 8, 0 ],
            [ RationalField() | -5, -10, -10, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 18, 0, 0, 0 ],
            [ RationalField() | 28, 20, 0, -20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | 9, 8, 0, -8 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 30, 16, 0, -16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0 ],
            [ RationalField() | -1, 4, -4, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0 ],
            [ RationalField() | 8, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 3, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0 ],
            [ RationalField() | -1, 2, 0, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | -2, 0, 0, 0 ],
            [ RationalField() | 34, 0, 0, 0 ],
            [ RationalField() | 4, -4, 0, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | -1, 0, -4, 0 ],
            [ RationalField() | 3, 4, -2, -2 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 0, 0, 0 ],
            [ RationalField() | 10, 2, 0, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -5, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0 ],
            [ RationalField() | -1, -4, -2, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0 ],
            [ RationalField() | 6, 4, 0, -4 ]
        ]
    ]
}
;
E7_ELTS8 := 
{ PowerSequence(PowerSequence(CyclotomicField(16))) |
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -20, 0, 16, 0, 0, 0, -16, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 0, -32, 0, 0, 0, 32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, -8, 0, 0, 0, 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -14, 0, 0, 0, 14, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 35, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 0, -12, 0, 0, 0, 12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 39, 0, -28, 0, 0, 0, 28, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 6, 0, 0, 0, -6, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 0, -16, 0, 0, 0, 16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, -8, 0, 0, 0, 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 4, 0, 0, 0, -4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 0, 12, 0, 0, 0, -12, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 8, 0, 0, 0, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -12, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 4, 0, 0, 0, -4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, -2, 0, 0, 0, 2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, -4, 0, 0, 0, 4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 12, 0, 0, 0, -12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 67, 0, 32, 0, 0, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 27, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 12, 0, -14, 0, 0, 0, 14, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 0, -20, 0, 0, 0, 20, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 0, 12, 0, 0, 0, -12, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -6, 0, 0, 0, 6, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 12, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -12, 0, 14, 0, 0, 0, -14, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 0, -20, 0, 0, 0, 20, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 2, 0, 0, 0, -2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, -4, 0, 0, 0, 4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 8, 0, 0, 0, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, -4, 0, 0, 0, 4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, -2, 0, 0, 0, 2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 4, 0, 0, 0, -4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 11, 0, -8, 0, 0, 0, 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 26, 0, 0, 0, -26, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 79, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 0, -16, 0, 0, 0, 16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -12, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 21, 0, 16, 0, 0, 0, -16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 2, 0, 0, 0, -2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, -6, 0, 0, 0, 6, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 8, 0, 0, 0, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -2, 0, 0, 0, 2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 11, 0, 8, 0, 0, 0, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 0, 16, 0, 0, 0, -16, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 0, 32, 0, 0, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -20, 0, -12, 0, 0, 0, 12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 39, 0, 28, 0, 0, 0, -28, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 0, 16, 0, 0, 0, -16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -20, 0, 12, 0, 0, 0, -12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 39, 0, -28, 0, 0, 0, 28, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, -12, 0, 0, 0, 12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 67, 0, -32, 0, 0, 0, 32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -2, 0, 0, 0, 2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 11, 0, -8, 0, 0, 0, 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -20, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 35, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -16, 0, 0, 0, 16, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 45, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -12, 0, -14, 0, 0, 0, 14, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 0, 20, 0, 0, 0, -20, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -32, 0, -12, 0, 0, 0, 12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 67, 0, 32, 0, 0, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -12, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 21, 0, -16, 0, 0, 0, 16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, -4, 0, 0, 0, 4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -2, 0, 0, 0, 2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -32, 0, 12, 0, 0, 0, -12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 67, 0, -32, 0, 0, 0, 32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 2, 0, 0, 0, -2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, -6, 0, 0, 0, 6, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, -8, 0, 0, 0, 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 0, 16, 0, 0, 0, -16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 0, -16, 0, 0, 0, 16, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 0, -32, 0, 0, 0, 32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 16, 0, 0, 0, -16, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 45, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -20, 0, -16, 0, 0, 0, 16, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 0, 32, 0, 0, 0, -32, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 12, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 21, 0, 16, 0, 0, 0, -16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 12, 0, 14, 0, 0, 0, -14, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 0, 20, 0, 0, 0, -20, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 6, 0, 0, 0, -6, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, 8, 0, 0, 0, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 2, 0, 0, 0, -2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 4, 0, 0, 0, -4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -26, 0, 0, 0, 26, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 79, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, -8, 0, 0, 0, 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -5, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -56, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 14, 0, 0, 0, -14, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 133, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 35, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 6, 0, 0, 0, -6, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 17, 0, -8, 0, 0, 0, 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 2, 0, 0, 0, -2, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 12, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 21, 0, -16, 0, 0, 0, 16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 35, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 4, 0, 0, 0, -4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, -8, 0, 0, 0, 8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 0, -12, 0, 0, 0, 12, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, -4, 0, 0, 0, 4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 0, -12, 0, 0, 0, 12, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -32, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 8, 0, 0, 0, -8, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 27, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 0, 12, 0, 0, 0, -12, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 39, 0, 28, 0, 0, 0, -28, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -8, 0, -4, 0, 0, 0, 4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 11, 0, 8, 0, 0, 0, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | -8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 4, 0, 0, 0, -4, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 8, 0, 0, 0, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(16)) |
        [ CyclotomicField(16) |
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(16) |
            [ RationalField() | 5, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E8_ELTS8 := 
{ PowerSequence(CyclotomicField(8)) |
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 2, -4, 0, 4 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 10, 8, 0, -8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 64, 0, 0, 0 ],
        [ RationalField() | 12, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 6, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | -4, 0, 0, 0 ],
        [ RationalField() | 38, -28, 0, 28 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 82, 52, 0, -52 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 2, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | -4, 0, 0, 0 ],
        [ RationalField() | 6, 4, 0, -4 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 64, 0, 0, 0 ],
        [ RationalField() | -4, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | -2, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | -4, 0, 0, 0 ],
        [ RationalField() | 6, -4, 0, 4 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 16, -8, 0, 8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 82, -52, 0, 52 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | -4, 0, 0, 0 ],
        [ RationalField() | 38, 28, 0, -28 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 64, 0, 0, 0 ],
        [ RationalField() | 44, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ],
        [ RationalField() | 48, -32, 0, 32 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 30, 16, 0, -16 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 30, -16, 0, 16 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 14, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 64, 0, 0, 0 ],
        [ RationalField() | 8, -8, 0, 8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 64, 48, 0, -48 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 10, -8, 0, 8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 132, 0, 0, 0 ],
        [ RationalField() | 134, 56, 0, -56 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 64, -48, 0, 48 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 4, 4, 0, -4 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 66, 32, 0, -32 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 64, 0, 0, 0 ],
        [ RationalField() | 8, 8, 0, -8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 132, 0, 0, 0 ],
        [ RationalField() | -6, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 4, -4, 0, 4 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 132, 0, 0, 0 ],
        [ RationalField() | 26, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 18, -12, 0, 12 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ],
        [ RationalField() | 20, 16, 0, -16 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | -4, 0, 0, 0 ],
        [ RationalField() | 2, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 64, 0, 0, 0 ],
        [ RationalField() | 92, 64, 0, -64 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | 66, -32, 0, 32 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ],
        [ RationalField() | 16, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 132, 0, 0, 0 ],
        [ RationalField() | 6, 8, 0, -8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 132, 0, 0, 0 ],
        [ RationalField() | 134, -56, 0, 56 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 64, 0, 0, 0 ],
        [ RationalField() | 92, -64, 0, 64 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 2, 4, 0, -4 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 36, -20, 0, 20 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 36, 20, 0, -20 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | -4, 0, 0, 0 ],
        [ RationalField() | 34, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ],
        [ RationalField() | 48, 32, 0, -32 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 78, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 4, 0, 0, 0 ],
        [ RationalField() | -2, 0, 0, 0 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0 ],
        [ RationalField() | 16, 8, 0, -8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 132, 0, 0, 0 ],
        [ RationalField() | 6, -8, 0, 8 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | -8, 0, 0, 0 ],
        [ RationalField() | 0, 0, 0, 0 ],
        [ RationalField() | 20, -16, 0, 16 ]
    ],
    [ CyclotomicField(8) |
        [ RationalField() | 24, 0, 0, 0 ],
        [ RationalField() | 28, 0, 0, 0 ],
        [ RationalField() | 18, 12, 0, -12 ]
    ]
}
;
