G2_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -1 ],
        [ RationalField() | -2 ]
    ]
}
;
F4_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | -6 ],
        [ RationalField() | 20 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | 2 ],
        [ RationalField() | -4 ]
    ]
}
;
E6_ELTS2 := 
{ PowerSequence(PowerSequence(RationalField())) |
    [ PowerSequence(RationalField()) |
        [ RationalField() | 3 ],
        [ RationalField() | -2 ]
    ],
    [ PowerSequence(RationalField()) |
        [ RationalField() | -5 ],
        [ RationalField() | 14 ]
    ]
}
;
E7_ELTS2 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -8, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -56, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 133, 0 ]
        ]
    ]
}
;
E8_ELTS2 := 
{ PowerSequence(RationalField()) |
    [ RationalField() | -8 ],
    [ RationalField() | 24 ]
}
;
