G2_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ]
    ]
}
;
F4_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 8, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ]
}
;
E6_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 9, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -27, 0, 0, -27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -9, 0, 0, -9, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 15, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 0, 0, 0, 27, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 78, 0, 0, 0, 0, 0 ]
        ]
    ]
}
;
E7_ELTS3 := 
{ PowerSequence(PowerSequence(CyclotomicField(3))) |
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -25, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 52, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | -7, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 20, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | 34, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(3)) |
        [ CyclotomicField(3) |
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(3) |
            [ RationalField() | -2, 0 ]
        ]
    ]
}
;
E8_ELTS3 := 
{ PowerSequence(CyclotomicField(3)) |
    [ CyclotomicField(3) |
        [ RationalField() | 5, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 77, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | 14, 0 ]
    ],
    [ CyclotomicField(3) |
        [ RationalField() | -4, 0 ]
    ]
}
;
