G2_ELTS4 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -1, 0 ],
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -1, 0 ],
            [ RationalField() | 3, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 2, 0 ]
        ]
    ]
}
;
F4_ELTS4 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 4, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | 2, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -6, 0 ],
            [ RationalField() | 6, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 20, 0 ],
            [ RationalField() | 8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -6, 0 ],
            [ RationalField() | -2, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 20, 0 ],
            [ RationalField() | 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 2, 0 ],
            [ RationalField() | 14, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -4, 0 ],
            [ RationalField() | 20, 0 ]
        ]
    ]
}
;
E6_ELTS4 := 
{ PowerSequence(PowerSequence(CyclotomicField(4))) |
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -5, 0 ],
            [ RationalField() | -9, 16 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 14, 0 ],
            [ RationalField() | 46, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 3, 0 ],
            [ RationalField() | 3, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -5, 0 ],
            [ RationalField() | 7, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 14, 0 ],
            [ RationalField() | 14, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -5, 0 ],
            [ RationalField() | -1, 4 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 14, 0 ],
            [ RationalField() | 6, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -5, 0 ],
            [ RationalField() | -1, -4 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 14, 0 ],
            [ RationalField() | 6, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 3, 0 ],
            [ RationalField() | -5, 8 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 18, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 3, 0 ],
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -5, 0 ],
            [ RationalField() | -9, -16 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 14, 0 ],
            [ RationalField() | 46, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 3, 0 ],
            [ RationalField() | -5, -8 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 18, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | -5, 0 ],
            [ RationalField() | -1, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | 14, 0 ],
            [ RationalField() | -2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(4)) |
        [ CyclotomicField(4) |
            [ RationalField() | 3, 0 ],
            [ RationalField() | 15, 0 ]
        ],
        [ CyclotomicField(4) |
            [ RationalField() | -2, 0 ],
            [ RationalField() | 34, 0 ]
        ]
    ]
}
;
E7_ELTS4 := 
{ PowerSequence(PowerSequence(CyclotomicField(8))) |
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -8, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 29, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | -3, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -8, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -56, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 133, 0, 0, 0 ],
            [ RationalField() | 25, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 9, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | 8, 0, 0, 0 ],
            [ RationalField() | -32, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 5, 0, 0, 0 ],
            [ RationalField() | 65, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(8)) |
        [ CyclotomicField(8) |
            [ RationalField() | -56, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(8) |
            [ RationalField() | 133, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0 ]
        ]
    ]
}
;
E8_ELTS4 := 
{ PowerSequence(CyclotomicField(4)) |
    [ CyclotomicField(4) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | -4, 0 ]
    ],
    [ CyclotomicField(4) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 64, 0 ]
    ],
    [ CyclotomicField(4) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 0, 0 ]
    ],
    [ CyclotomicField(4) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 132, 0 ]
    ],
    [ CyclotomicField(4) |
        [ RationalField() | -8, 0 ],
        [ RationalField() | 8, 0 ]
    ],
    [ CyclotomicField(4) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 28, 0 ]
    ],
    [ CyclotomicField(4) |
        [ RationalField() | 24, 0 ],
        [ RationalField() | 4, 0 ]
    ]
}
;
