G2_ELTS5 := 
{ PowerSequence(PowerSequence(CyclotomicField(5))) |
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, 1, 1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 1, 0, -1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 3, 0, 2, 2 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 3, 0, 3, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 1, 0, -2, -2 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, -3, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -1, 0, -1, -1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 2, 0, 1, 1 ]
        ]
    ]
}
;
F4_ELTS5 := 
{ PowerSequence(PowerSequence(CyclotomicField(5))) |
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -1, 0, 1, 1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 1, 0, -2, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 8, 0, -6, -6 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 8, 0, -13, -13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -2, 0, -1, -1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 3, 0, 2, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 14, 0, 6, 6 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 21, 0, 13, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 7, 0, 7, 7 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 15, 0, 1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, -7, -7 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 14, 0, -1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 1, 0, 0, 0 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 2, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 5, 0, 3, 3 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 4, 0, 4, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 2, 0, -3, -3 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, -4, -4 ]
        ]
    ]
}
;
E6_ELTS5 := 
{ PowerSequence(PowerSequence(CyclotomicField(5))) |
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 0, 10, 16, 1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 30, 0, -16, -16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -8, -5, 0, -10 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 23, 0, 15, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, 1, 1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, -1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 1, 5, 3, 3 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 4, 0, -3, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 0, 5, -4, 1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 15, 0, 4, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 9, 0, -6, -6 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 16, 0, -19, -19 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 15, 0, 6, 6 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 35, 0, 19, 19 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 4, 5, 9, 4 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 11, 0, -4, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 1, 0, -7, -7 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 14, 0, -8, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 2, 0, 0, 0 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 3, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -1, 15, -1, 9 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 46, 0, 16, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 8, 0, 7, 7 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 22, 0, 8, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -1, 0, -1, -1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 1, 0, 1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 6, 0, 3, 3 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 9, 0, 7, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -2, 0, -3, 2 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 7, 0, 3, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 2, 10, 10, 5 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 8, 0, -15, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -16, -15, -6, -16 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 46, 0, 16, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -5, -5, -4, -9 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 15, 0, 4, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -4, -5, -2, -2 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 4, 0, -3, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -2, 0, 2, -3 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 7, 0, 3, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -1, -5, -1, 4 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 11, 0, -4, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -3, 5, -5, 5 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 23, 0, 15, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 3, 0, -3, -3 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 2, 0, -7, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -8, -10, -5, 0 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 8, 0, -15, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -10, -10, -9, 6 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 30, 0, -16, -16 ]
        ]
    ]
}
;
E7_ELTS5 := 
{ PowerSequence(PowerSequence(CyclotomicField(5))) |
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -4, 0, 5, 5 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 3, 0, -10, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 5, 0, 8, 8 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 15, 0, 4, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 6, 0, 0, 0 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 8, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -7, 0, 14, 14 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 14, 0, -28, -28 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -8, 0, 7, 7 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 21, 0, -9, -9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 4, 0, -14, -14 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 17, 0, -22, -22 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -1, 0, 26, 26 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 52, 0, -27, -27 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 14, 0, 6, 6 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 22, 0, 13, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 18, 0, 14, 14 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 39, 0, 22, 22 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -1, 0, 1, 1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 2, 0, -2, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -3, 0, -8, -8 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 11, 0, -4, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -9, 0, -5, -5 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 13, 0, 10, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -27, 0, -26, -26 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 79, 0, 27, 27 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -15, 0, -7, -7 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 30, 0, 9, 9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, -2, -2 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 0, 0, -1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -2, 0, -1, -1 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 4, 0, 2, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 32, 0, 12, 12 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 66, 0, 31, 31 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 2, 0, 2, 2 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 1, 0, 1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 20, 0, -12, -12 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 35, 0, -31, -31 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | 8, 0, -6, -6 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 9, 0, -13, -13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(5)) |
        [ CyclotomicField(5) |
            [ RationalField() | -21, 0, -14, -14 ]
        ],
        [ CyclotomicField(5) |
            [ RationalField() | 42, 0, 28, 28 ]
        ]
    ]
}
;
E8_ELTS5 := 
{ PowerSequence(CyclotomicField(5)) |
    [ CyclotomicField(5) |
        [ RationalField() | 3, 0, 0, 0 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | -2, 0, 0, 0 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 28, 0, -50, -50 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 28, 0, -25, -25 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 133, 0, 55, 55 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 8, 0, -20, -20 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 23, 0, 0, 0 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 78, 0, 50, 50 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 53, 0, 25, 25 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 28, 0, 20, 20 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 8, 0, 5, 5 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 3, 0, -5, -5 ]
    ],
    [ CyclotomicField(5) |
        [ RationalField() | 78, 0, -55, -55 ]
    ]
}
;
