G2_ELTS7 := 
{ PowerSequence(PowerSequence(CyclotomicField(7))) |
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 2, 1, 1, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, 0, -1, -1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, 2, 0, 0, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 4, 1, 1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, -1, -2, -2, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -1, 0, 0, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -1, 1, 1, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, 1, 1, 1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, -2, -2, -2, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -3, -4, -4, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, 0, 2, 2, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -1, 3, 3, -1 ]
        ]
    ]
}
;
F4_ELTS7 := 
{ PowerSequence(PowerSequence(CyclotomicField(7))) |
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, 6, 0, 0, 6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 22, 0, 14, 1, 1, 14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 5, 0, 4, 3, 3, 4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, 3, -1, -1, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -7, -8, -8, -7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, -1, -8, -8, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 6, 3, 3, 6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 10, 0, 10, 4, 4, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 8, 1, 1, 8 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 22, 0, 8, 7, 7, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, 0, -3, -4, -4, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, 3, -1, -1, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, -1, 3, 3, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -4, -3, -3, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -3, 1, 1, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, 1, 4, 4, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 5, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -1, 0, 0, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 0, 1, 1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 1, 1, 1, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 1, 0, 0, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -6, -6, -6, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -13, -14, -14, -13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, 0, 6, 6, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 21, 0, -1, 13, 13, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -3, -6, -6, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -6, -10, -10, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, 4, 1, 1, 4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, 1, 4, 4, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, -1, 7, 7, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 15, 0, -7, 1, 1, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 5, 0, -3, 3, 3, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, -4, 6, 6, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 0, -1, -1, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -1, -1, -1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, -1, -4, -4, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -4, -3, -3, -4 ]
        ]
    ]
}
;
E6_ELTS7 := 
{ PowerSequence(PowerSequence(CyclotomicField(7))) |
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, 4, 3, 3, 4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, 7, 2, 2, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -1, -4, -4, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -5, -7, -7, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -3, -3, -2, -3, -1, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 2, 0, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 15, 0, 0, 6, 6, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 35, 0, -1, 19, 19, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -10, -10, 0, -5, -10, -8 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 23, 0, -5, 15, 15, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, -1, -4, -1, -5, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 2, 1, 1, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, -1, -1, -1, 9, 15 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 30, 0, -16, -16, -16, -16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, -3, 3, 3, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, -7, 9, 9, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 10, 0, 16, 0, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 46, 0, 16, 0, 0, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 6, 2, -2, 1, 4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -7, 0, 0, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, -4, 0, -1, -3, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -1, 1, 1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -4, -5, 2, 0, -6, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, -5, 7, 7, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -4, -6, -5, -2, 2, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -7, -12, -12, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, 8, -2, 8, -2, 3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 28, 0, 20, 5, 5, 20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, -1, 9, 4, 0, 4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 21, 0, 6, 5, 5, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -4, -5, -3, -2, -1, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -5, -6, -6, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 10, 5, 0, 5, 6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, -9, 5, 5, -9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 5, 5, 4, 3, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -5, -6, -6, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 2, -4, 4, -2, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 15, 0, 7, 7, 7, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -4, 1, -5, 5, -5, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 25, 0, 14, 9, 9, 14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, -2, 1, -1, -2, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 0, 2, 2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -6, -4, -2, -7, -2, -8 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, 12, 5, 5, 12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 6, 6, 8, 4, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -7, -12, -12, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 1, 2, 3, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -2, -2, -2, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, 4, 1, 1, 4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 5, 5, 5, 5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 10, 2, 0, 5, 10 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 23, 0, -5, 15, 15, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, -1, -1, -1, 2, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -2, -2, -2, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 2, 0, 0, 1, 3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 0, 2, 2, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -9, -10, -4, -5, -10, -5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, -9, 5, 5, -9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 2, 3, 3, 4, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, -1, -2, -2, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 1, -1, -4, 0, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 2, 1, 1, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 16, 0, 0, 1, 10 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 46, 0, 0, 16, 16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 6, 3, 3, 6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 18, 0, 16, 7, 7, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 7, 7, 0, 7, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 22, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -1, 7, 7, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 22, 0, -8, 8, 8, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 8, 1, 1, 8 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 30, 0, 16, 8, 8, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -8, -7, -7, 0, -7, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 22, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, -6, -6, -6, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, -19, -20, -20, -19 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -5, -5, -5, -3, 5, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -15, -20, -20, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -4, -5, -5, 0, 1, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, -5, -14, -14, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 5, 1, 5, 1, 5, 10 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 21, 0, 6, 5, 5, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, 4, -4, 2, -3, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, 12, 5, 5, 12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 5, 3, -1, 5, 7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, -5, 7, 7, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -3, -1, 1, -2, 1, -4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 6, 1, 1, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, 1, -3, 2, -1, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 6, 1, 1, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, -2, -3, 2, 1, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, -1, -2, -2, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -5, -1, -1, -6, 4, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 25, 0, 14, 9, 9, 14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, -7, -8, -8, -7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, -8, -16, -16, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 3, 1, -2, 3, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, -1, 5, 5, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 3, 0, 2, 0, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 2, 0, 0, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -4, -3, -1, 0, -5, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, -1, 5, 5, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, -1, 0, 0, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, -1, 1, 1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -2, -2, -3, -4, 2, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 15, 0, 7, 7, 7, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -10, -8, -5, -10, 0, -10 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 28, 0, 20, 5, 5, 20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 1, 16, 10, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 30, 0, -16, -16, -16, -16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 3, 4, 5, 1, 3, 4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -1, 1, 1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, 1, 1, 1, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, 2, 1, 1, 2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 5, 10, 6, 5, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, -5, -14, -14, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -10, -10, -9, -10, 6, -10 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 46, 0, 16, 0, 0, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 5, -4, -4, -5, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 15, 0, -1, -6, -6, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, 4, 0, 9, 4, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, -5, 1, 1, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, 3, 8, 6, 4, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 0, -7, -7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -5, -5, -5, -10, -9, -9 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 15, 0, -1, -6, -6, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -3, -6, -6, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -9, -16, -16, -9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 5, 10, 10, 2, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -15, -20, -20, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, -4, -5, 0, 5, -4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, -5, 1, 1, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -16, -16, -6, -15, -16, -16 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 46, 0, 0, 16, 16, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -4, -6, -2, -5, -8, -4 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -7, 0, 0, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -3, 1, 1, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, -2, 5, 5, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -1, 3, 3, -1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -5, 0, 0, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 15, 0, 6, 0, 0, 6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 36, 0, 20, 1, 1, 20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, -3, -4, -4, -3 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 0, -5, -5, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, -3, -1, 1, 3, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 0, -7, -7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 0, -1, -1, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -1, -2, -2, -1 ]
        ]
    ]
}
;
E7_ELTS7 := 
{ PowerSequence(PowerSequence(CyclotomicField(7))) |
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, -5, -5, -5, -5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, -3, -4, -4, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, -5, 9, 9, -5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 21, 0, -10, 10, 10, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, -2, -8, -8, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, -7, -15, -15, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 20, 0, -12, -12, -12, -12 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 35, 0, -31, -32, -32, -31 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -27, 0, -27, -26, -26, -27 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 79, 0, 27, 0, 0, 27 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -7, 0, 8, -1, -1, 8 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 17, 0, -13, 1, 1, -13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -15, 0, -12, -5, -5, -12 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 28, 0, 25, 10, 10, 25 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -2, 0, 0, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -3, 1, 1, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -14, -16, -16, -14 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 17, 0, -22, -32, -32, -22 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 20, 0, 12, 6, 6, 12 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 37, 0, 28, 13, 13, 28 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 20, 0, 16, 2, 2, 16 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 49, 0, 32, 10, 10, 32 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -10, 0, 7, -9, -9, 7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 31, 0, -15, 10, 10, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -10, 0, -7, -2, -2, -7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 17, 0, 13, 3, 3, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 0, -2, -2, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -1, -4, -4, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -6, -8, -8, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -6, -13, -13, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, 2, 2, 2, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -3, -4, -4, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, 8, 6, 6, 8 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 24, 0, 15, 8, 8, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -7, 0, 14, -7, -7, 14 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 42, 0, -7, 28, 28, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -6, 0, 1, -5, -5, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, -8, 0, 0, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, 5, 6, 6, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 0, -8, -8, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -3, 0, -2, 0, 0, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 4, 1, 1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -7, 0, -6, -1, -1, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 17, 0, 8, 8, 8, 8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -3, 0, 0, -2, -2, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -1, 3, 3, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 5, 0, 0, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, 4, 1, 1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, -7, 0, 0, -7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, 0, 7, 7, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 1, 2, 2, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, -1, 0, 0, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 21, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, -2, -1, -1, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 2, 0, 0, -1, -1, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -3, 0, 5, 7, 7, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, -10, -13, -13, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, 2, 2, 2, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, 4, 3, 3, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, 9, 16, 16, 9 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 21, 0, -10, -25, -25, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 0, -7, -7, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, -7, -7, -7, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 1, 6, 6, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -6, -6, -6, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 1, 27, 27, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 52, 0, -27, -27, -27, -27 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 6, 0, -2, 6, 6, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, -7, 6, 6, -7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 18, 0, -2, 14, 14, -2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 39, 0, -10, 22, 22, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -6, 0, -6, -5, -5, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 6, 0, 0, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 1, 0, 15, 9, 9, 15 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 30, 0, -1, -7, -7, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 32, 0, 12, 0, 0, 12 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 67, 0, 32, 1, 1, 32 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -15, 0, -9, -8, -8, -9 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 30, 0, 14, 13, 13, 14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -8, 0, -9, 6, 6, -9 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 37, 0, 7, 6, 6, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -10, 0, 5, -7, -7, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 18, 0, -10, 15, 15, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, -6, 6, 6, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 24, 0, -13, 15, 15, -13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 1, -1, -1, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, 1, 1, 1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 4, 0, 0, 5, 5, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 10, 0, -1, 3, 3, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, 14, 5, 5, 14 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 31, 0, 20, 10, 10, 20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -14, 0, -6, -15, -15, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 31, 0, -6, 1, 1, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -3, 0, 7, 12, 12, 7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 3, 0, -15, -25, -25, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, 26, -1, -1, 26 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 79, 0, 0, 27, 27, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -6, 2, 2, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, -8, 7, 7, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -1, 0, 5, -1, -1, 5 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, 0, 6, 6, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -21, 0, -21, -14, -14, -21 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 49, 0, 35, 7, 7, 35 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 0, 0, 7, 21, 21, 7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, -28, -35, -35, -28 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 32, 0, 0, 12, 12, 0 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 66, 0, -1, 31, 31, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, -6, -12, -12, -6 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 9, 0, -15, -28, -28, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -6, 0, 1, 9, 9, 1 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, -1, -14, -14, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -17, 0, -16, -7, -7, -16 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 46, 0, 25, 15, 15, 25 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 7, 0, 7, 7, 7, 7 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, 7, 0, 0, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -3, 0, -9, -14, -14, -9 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 11, 0, -10, -20, -20, -10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | -8, 0, 2, -5, -5, 2 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 14, 0, -3, 10, 10, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(7)) |
        [ CyclotomicField(7) |
            [ RationalField() | 8, 0, 8, 2, 2, 8 ]
        ],
        [ CyclotomicField(7) |
            [ RationalField() | 16, 0, 13, 7, 7, 13 ]
        ]
    ]
}
;
E8_ELTS7 := 
{ PowerSequence(CyclotomicField(7)) |
    [ CyclotomicField(7) |
        [ RationalField() | 78, 0, -55, -56, -56, -55 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 7, 0, 1, 4, 4, 1 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 3, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 21, 0, -1, 13, 13, -1 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 134, 0, 56, 1, 1, 56 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 17, 0, -14, 7, 7, -14 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 28, 0, -50, -64, -64, -50 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 35, 0, -20, 11, 11, -20 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 0, 0, -1, -1, -1, -1 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 24, 0, -11, 18, 18, -11 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 78, 0, -14, 50, 50, -14 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 10, 0, -7, -21, -21, -7 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 8, 0, -13, -14, -14, -13 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 6, 0, -18, -29, -29, -18 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 133, 0, -1, 55, 55, -1 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 24, 0, -11, -31, -31, -11 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 22, 0, 8, 7, 7, 8 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 92, 0, 64, 14, 14, 64 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 55, 0, -25, 27, 27, -25 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 36, 0, -20, 28, 28, -20 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 1, 0, 0, 1, 1, 0 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 1, 0, 1, 0, 0, 1 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 3, 0, -4, -3, -3, -4 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 22, 0, 14, 1, 1, 14 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 10, 0, 10, 4, 4, 10 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 6, 0, 3, -1, -1, 3 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 55, 0, 31, 20, 20, 31 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 35, 0, 29, 11, 11, 29 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 80, 0, 52, 25, 25, 52 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 8, 0, -28, -48, -48, -28 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 14, 0, -1, -8, -8, -1 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 28, 0, -27, -52, -52, -27 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 52, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 15, 0, -7, 1, 1, -7 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 56, 0, 48, 20, 20, 48 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 31, 0, 21, 14, 14, 21 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 6, 0, -4, 6, 6, -4 ]
    ],
    [ CyclotomicField(7) |
        [ RationalField() | 0, 0, -6, -10, -10, -6 ]
    ]
}
;
