G2_ELTS9 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 1, -1, 0, 1, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, -1, 1, 0, 0, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 2, -2, 0, 0, -2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 3, -3, 0, -1, -4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 2, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, 4, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, -2, 2, 0, -1, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 3, -2, 2, 0, -2, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -4, 4, 0, -3, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, -1, 1, 0, 0, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, -1, -1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, 2, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, -1, -2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 5, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, -1, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, 1, 0 ]
        ]
    ]
}
;
F4_ELTS9 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 6, -6, 0, 0, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 13, -13, 0, -1, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -3, 3, 0, 0, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -3, 3, 0, -3, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 1, -1, 0, -1, -2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, 0, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, -3, 3, 0, 0, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -5, 5, 0, -1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, -3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, -4, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 1, -1, 0, -1, -2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 3, -3, 0, 3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 4, -4, 0, 5, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -2, 2, 0, -1, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, -8, 8, 0, -7, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, -8, 8, 0, -1, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 7, -7, 0, -1, -8 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 1, -1, 0, -7, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 1, -1, 0, 2, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 1, -1, 0, 2, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, -3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 3, -3, 0, 0, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -3, 3, 0, -3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, -6, 6, 0, -3, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -12, 12, 0, -6, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, 6, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 6, -6, 0, 3, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 3, -3, 0, -3, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 6, -6, 0, -6, -12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 3, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -6, 6, 0, -3, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -3, 3, 0, 3, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, 3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, 3, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -2, 2, 0, -1, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 4, -4, 0, 5, 1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 4, -4, 0, 8, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 1, -1, 0, -4, -5 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 4, -4, 0, -4, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, -6, 6, 0, -6, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, -14, 14, 0, -13, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, -5, 5, 0, -1, 4 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -8, 8, 0, -4, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 8, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0, 6, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 1, -1, 0, 14, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 3, -3, 0, 6, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 6, -6, 0, 12, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, -3, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -3, 3, 0, -6, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -1, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 1, -1, 0, 8, 7 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 7, -7, 0, 8, 1 ]
        ]
    ]
}
;
E6_ELTS9 := 
{ PowerSequence(PowerSequence(CyclotomicField(27))) |
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -6, 0, 0, -3, 0, 0, -3, 0, 0, -6, 0, 0, 0, 0, 0,
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -7, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, 2, 0, 0, 2, 0, 0, -2, 0, 0, -5, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, -1, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, 5, 0, 0, 5, 0, 0, 4, 0, 0, 10, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -10, 0, 0,
            -11, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, -3, 0, 0, 
            -6, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, -2, 0, 0, -2, 0, 0, -1, 0, 0, -1, 0, 
            0, -1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 4, 0, 0, -2, 0, 0, -4, 0, 0, 2, 0, 0, 
            -7, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -7, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 4, 0, 0, -2, 0, 0, -2, 0, 0, 2, 0, 0, -4, 0, 0, 
            -7, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, -1, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, -5, 0, 0, -5, 0, 0, 5, 0, 0, -4, 0, 0, 
            -10, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 10, 0, 0, -10, 0, 0, 0, 0, 0, 11, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -5, 0, 0, 5, 0, 0, -3, 0, 0, -4, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, -10, 0, 0, -4, 0, 0, 4, 0, 0, -5, 0, 
            0, -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 10, 0, 0, -10, 0, 0, 0, 0, 0, 11, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 15, 0, 0, 6, 0, 0, -6, 0, 0, 0, 0, 0, 0, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, 19, 0, 0, -19, 0, 0, 0, 0, 0, -1, 0, 
            0, -20, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -5, 0, 0, 4, 0, 0, 10, 0, 0, -4, 0, 0, -1, 0, 0,
            5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 10, 0, 0, -10, 0, 0, 0, 0, 0, 11, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -6, 0, 0, -3, 0, 0, 3, 0, 0, -3, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, 9, 0, 0, 
            0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 1, 0, 0, -2, 0, 0, 2, 0, 0, -1, 0, 0, 
            -1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 9, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, -1, 0, 0, 
            -8, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, -8, 0, 0, 
            -16, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -27, 0, 0, 0, 0, 0, 0, 0, 0, -27, 0, 0, 0, 0, 0,
            0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, -6, 0, 0, 0, 0, 0, 0, 0, 0, 
            -15, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, -2, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -5, 0, 0, -5, 0, 0, -5, 0, 0, -4, 0, 0, -4, 0, 
            0, 5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -10, 0, 0,
            -11, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -27, 0, 0, 0, 0, 0, 0, 0, 0, -27, 0, 0, 0, 0, 0,
            0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, -3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 1, 0, 0, -2, 0, 0, -1, 0, 0, 2, 0, 0, 
            -1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -5, 0, 0, -1, 0, 0, 6, 0, 0, -1, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, 13, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, -1, 0, 0, -1, 0, 0, -2, 0, 0, 1, 0, 0,
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, 2, 0, 0, 3, 0, 0, 2, 0, 0, 1, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, -2, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 6, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 3, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, 8, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, -2, 0, 0, 7, 0, 0, -4, 0, 0, -4, 0, 0,
            5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 8, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 4, 0, 0, -1, 0, 0, -3, 0, 0, -1, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -5, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -6, 0, 0, 1, 0, 0, 5, 0, 0, -6, 0, 0, -4, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, 13, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -6, 0, 0, -3, 0, 0, 9, 0, 0, -3, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, 18, 0, 0, 
            9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -9, 0, 0, -8, 0, 0, -1, 0, 0, -9, 0, 0, -7, 0, 
            0, 7, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, -8, 0, 0, 
            -16, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, 8, 0, 0, 9, 0, 0, 8, 0, 0, 1, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, -8, 0, 0, 
            -16, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 3, 0, 0, 6, 0, 0, -3, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, 9, 0, 0, 
            0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 4, 0, 0, 5, 0, 0, 6, 0, 0, 5, 0, 0, 4, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, -8, 0, 0, 
            -13, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 9, 0, 0, -6, 0, 0, 6, 0, 0, 0, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, -18, 0, 0, 18, 0, 0, 0, 0, 0, -9, 0, 
            0, 9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -5, 0, 0, 5, 0, 0, 3, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -6, 0, 0, 0, 0, 0, 0, 0, 0, -3, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 1, 0, 0, 10, 0, 0, 5, 0, 0, 5, 0, 0, 5,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -10, 0, 0,
            -11, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -4, 0, 0, 5, 0, 0, -4, 0, 0, -5, 0, 0, 10, 0, 0,
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, -11, 0, 0, 11, 0, 0, 0, 0, 0, -1, 0, 
            0, 10, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 3, 0, 0, -3, 0, 0, -3, 0, 0, 6, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -9, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 
            9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 5, 0, 0, -10, 0, 0, 5, 0, 0, 1, 0, 0, -5, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, -11, 0, 0, 11, 0, 0, 0, 0, 0, -1, 0, 
            0, 10, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, 2, 0, 0, -1, 0, 0, -2, 0, 0, 1, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 2,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0, -2, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 0, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -6, 0, 0, 3, 0, 0, 0, 0, 0, -6, 0, 0, 3, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -1, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 2, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, -3, 0, 0, 0, 0, 0, 0, 0, 0, 3,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 6, 0, 0, 3,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, 9, 0, 0, 
            0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -6, 0, 0, 4, 0, 0, -1, 0, 0, -6, 0, 0, 5, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -13, 0, 0, 13, 0, 0, 0, 0, 0, -5, 0, 
            0, 8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 6, 0, 0, -3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -1, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -9, 0, 0, -6, 0, 0, -3, 0, 0, -9, 0, 0, -3, 0, 
            0, 3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, -9, 0, 0, 
            -18, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, -2, 0, 0, -5, 0, 0, 2, 0, 0, -4, 0, 0,
            2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -7, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, -2, 0, 0, -5, 0, 0, -4, 0, 0, 2, 0, 0,
            2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, -1, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, 5, 0, 0, 2, 0, 0, 4, 0, 0, 7, 0, 0, 4, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, -1, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, -6, 0, 0, -3, 0, 0, -3, 0, 0, -3, 0, 
            0, 3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 
            -9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -6, 0, 0, -5, 0, 0, -4, 0, 0, -6, 0, 0, -1, 0, 
            0, 1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, -8, 0, 0, 
            -13, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 2,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 4, 0, 0, -5, 0, 0, 10, 0, 0, -1, 0, 0, -4, 0, 0,
            5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, -11, 0, 0, 11, 0, 0, 0, 0, 0, -1, 0, 
            0, 10, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, -2, 0, 0, -2, 0, 0, 2, 0, 0, 2, 0, 0, 
            -7, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 8, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, -15, 0, 0, 0, 0, 0, 0, 0, 0, -6, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, -1, 0, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, -3, 0, 0, 9, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, -18, 0, 0, 18, 0, 0, 0, 0, 0, -9, 0, 
            0, 9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 3, 0, 0, -3, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 6, 0, 0, 3,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 5, 0, 0, 5, 0, 0, -1, 0, 0, 1, 0, 0, 10, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 10, 0, 0, -10, 0, 0, 0, 0, 0, 11, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 4, 0, 0, -4, 0, 0, 3, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 1, 0, 0, 1, 0, 0, -1, 0, 0, 2, 0, 0, 
            -1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 5, 0, 0, 5, 0, 0, -4, 0, 0, 1, 0, 0, -5, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -10, 0, 0,
            -11, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -27, 0, 0, 0, 0, 0, 0, 0, 0, -27, 0, 0, 0, 0, 0,
            0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 0, 0, 0, 6,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0, -2, 0, 0,
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, -3, 0, 0, -3, 0, 0, 3, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -4, 0, 0, 6, 0, 0, -4, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -13, 0, 0, 13, 0, 0, 0, 0, 0, -5, 0, 
            0, 8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -9, 0, 0, 3, 0, 0, 6, 0, 0, -9, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, 18, 0, 0, 
            9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 4, 0, 0, -5, 0, 0, 5, 0, 0, -1, 0, 0, 
            5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, -11, 0, 0, 11, 0, 0, 0, 0, 0, -1, 0, 
            0, 10, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, -3, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 4, 0, 0, -5, 0, 0, -1, 0, 0, -1, 0, 0, 
            -10, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -10, 0, 0,
            -11, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -4, 0, 0, 3, 0, 0, -4, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -5, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -3, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, 8, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -5, 0, 0, -1, 0, 0, 3, 0, 0, -4, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, 4, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, 2, 0, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 7, 0, 0, -1, 0, 0, 9, 0, 0, -1, 0, 0, 
            7, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, -16, 0, 0, 16, 0, 0, 0, 0, 0, -8, 0, 
            0, 8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -4, 0, 0, 5, 0, 0, 5, 0, 0, -5, 0, 0, -5, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 10, 0, 0, -10, 0, 0, 0, 0, 0, 11, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 3, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -9, 0, 0, 3, 0, 0, -3, 0, 0, -9, 0, 0, 6, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, -18, 0, 0, 18, 0, 0, 0, 0, 0, -9, 0, 
            0, 9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 9, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 6, 0, 0, 3,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, 18, 0, 0, 
            9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -8, 0, 0, -7, 0, 0, 9, 0, 0, -7, 0, 0, 
            -8, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, 16, 0, 0, 
            8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 6,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 20, 0, 0, 
            19, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -15, 0, 0, 6, 0, 0, 6, 0, 0, -15, 0, 0, 0, 0, 0,
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 20, 0, 0, 
            19, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 3, 0, 0, 0, 0, 0, -3, 0, 0, 3, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, -6, 0, 0, 6, 0, 0, 0, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 3, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 6, 0, 0, 3,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, -1, 0, 0, 2, 0, 0, -2, 0, 0, -2, 0, 0,
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 4, 0, 0, 2,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -4, 0, 0, -3, 0, 0, 5, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, 4, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 15, 0, 0, -6, 0, 0, 6, 0, 0, 0, 0, 0, -6, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, -20, 0, 0, 20, 0, 0, 0, 0, 0, -19, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -15, 0, 0, 0, 0, 0, -6, 0, 0, -15, 0, 0, 6, 0, 
            0, -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, -20, 0, 0, 20, 0, 0, 0, 0, 0, -19, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, -7, 0, 0, 2, 0, 0, 4, 0, 0, -2, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 8, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 8, 0, 0, 7,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, 16, 0, 0, 
            8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 5, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, -3, 0, 0, 6, 0, 0, -3, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -1, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, -3, 0, 0, 0, 0, 0, -3, 0, 0, -3, 0, 0,
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 4, 0, 0, -1, 0, 0, 3, 0, 0, 5, 0, 0, 4,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, 4, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -27, 0, 0, 0, 0, 0, 0, 0, 0, -27, 0, 0, 0, 0, 0,
            0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 9,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -4, 0, 0, -10, 0, 0, -1, 0, 0, -5, 0, 0, -5, 0, 
            0, 4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -10, 0, 0,
            -11, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 1, 0, 0, -1, 0, 0, -3, 0, 0, 2, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, -2, 0, 0, 
            2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -2, 0, 0, -1, 0, 0, 3, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 4, 0, 0, 2,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, 5, 0, 0, -3, 0, 0, -4, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, 4, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, -7, 0, 0, 2, 0, 0, -2, 0, 0, -2, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -7, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -27, 0, 0, 0, 0, 0, 0, 0, 0, -27, 0, 0, 0, 0, 0,
            0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 4, 0, 0, -5, 0, 0, 2, 0, 0, 2, 0, 0, 2,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 8, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 4, 0, 0, 5, 0, 0, 0, 0, 0, -1, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, 4, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 9, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, -3, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, -9, 0, 0, 
            -18, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -2, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -15, 0, 0, -6, 0, 0, 0, 0, 0, -15, 0, 0, -6, 0, 
            0, 6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, 19, 0, 0, -19, 0, 0, 0, 0, 0, -1, 0, 
            0, -20, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 6, 0, 0, 9, 0, 0, 6, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 18, 0, 0, 9, 0, 0, -9, 0, 0, 0, 0, 0, -9, 0, 0, 
            -18, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 6, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -4, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, -8, 0, 0, 
            -13, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -27, 0, 0, 0, 0, 0, 0, 0, 0, -27, 0, 0, 0, 0, 0,
            0, 0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -5, 0, 0, -1, 0, 0, -3, 0, 0, -1, 0, 0,
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -5, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, 6, 0, 0, 3,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 1, 0, 0, 1, 0, 0, -1, 0, 0, -1, 0, 0, 
            -1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, 2, 0, 0, -1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 4, 0, 0, 7, 0, 0, 2, 0, 0, 2, 0, 0, 5,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, -1, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 6, 0, 0, -5, 0, 0, 5, 0, 0, 0, 0, 0, -1, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -13, 0, 0, 13, 0, 0, 0, 0, 0, -5, 0, 
            0, 8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, -3, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 
            -9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -1, 0, 0, 3, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, -2, 0, 0, 
            2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, -3, 0, 0, 0, 0, 0, 0, 0, 0, 
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -6, 0, 0, 6, 0, 0, 0, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -9, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 
            9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -5, 0, 0, 1, 0, 0, -5, 0, 0, -4, 0, 0, 5, 0, 0, 
            -10, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, -11, 0, 0, 11, 0, 0, 0, 0, 0, -1, 0, 
            0, 10, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, -3, 0, 0, 
            -6, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, -5, 0, 0, -4, 0, 0, 0, 0, 0, -4, 0, 0,
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -5, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 6, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 6,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, -20, 0, 0, 20, 0, 0, 0, 0, 0, -19, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 1, 0, 0, -5, 0, 0, -1, 0, 0, 5, 0, 0, 
            5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, 10, 0, 0, -10, 0, 0, 0, 0, 0, 11, 0, 
            0, 1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 1, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -3, 0, 0, 3, 0, 0, 0, 0, 0, -3, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 2,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, -2, 0, 0, 1, 0, 0, 2, 0, 0, -1, 0, 0, 
            -1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -6, 0, 0, -6, 0, 0, 15, 0, 0, -6, 0, 0,
            -6, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 20, 0, 0, 
            19, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 4, 0, 0, -2, 0, 0, 7, 0, 0, 2, 0, 0, 2, 0, 0, 5,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -7, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, -6, 0, 0, 6, 0, 0, 0, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 3, 0, 0, 6, 0, 0, 3, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -7, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -4, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0, 1, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -4, 0, 0, 5, 0, 0, 2, 0, 0, -2, 0, 0, 7, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -7, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -3, 0, 0, -3, 0, 0, 3, 0, 0, -3, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, -3, 0, 0, 0, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, -2, 0, 0, -1, 0, 0, -3, 0, 0, -1, 0, 
            0, 1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, -2, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, 2, 0, 0, -4, 0, 0, 4, 0, 0, -5, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -7, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 9, 0, 0, -8, 0, 0, 8, 0, 0, 0, 0, 0, -7, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, -16, 0, 0, 16, 0, 0, 0, 0, 0, -8, 0, 
            0, 8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, 6, 0, 0, 3, 0, 0, 6, 0, 0, 3, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 
            -9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -2, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 1, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, -2, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -2, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -4, 0, 0, 2, 0, 0, 2, 0, 0, -2, 0, 0, -5, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 8, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -9, 0, 0, 1, 0, 0, -7, 0, 0, -9, 0, 0, 8, 0, 0, 
            -8, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, -16, 0, 0, 16, 0, 0, 0, 0, 0, -8, 0, 
            0, 8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 6, 0, 0, 15, 0, 0, 6, 0, 0, 0,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 36, 0, 0, 19, 0, 0, -19, 0, 0, 0, 0, 0, -1, 0, 
            0, -20, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -2, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -6, 0, 0, 0, 0, 0, 3, 0, 0, -6, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, 8, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, -2, 0, 0, 
            2, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, -5, 0, 0, -4, 0, 0, 0, 0, 0, -1, 0, 0,
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 5, 0, 0, -5, 0, 0, 0, 0, 0, 4, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -4, 0, 0, -7, 0, 0, -4, 0, 0, -2, 0, 0, -2, 0, 
            0, -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 7, 0, 0, -7, 0, 0, 0, 0, 0, -1, 0, 0, 
            -8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 4, 0, 0, 5, 0, 0, 0, 0, 0, 5, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -5, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 1, 0, 0, 1, 0, 0, -1, 0, 0, -1, 0, 0, 
            2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 4, 0, 0, -4, 0, 0, -3, 0, 0, 5, 0, 0, 
            -5, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -4, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 6, 0, 0, 4, 0, 0, -4, 0, 0, 0, 0, 0, 5, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, 13, 0, 0, 
            5, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | -9, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 
            0, 0, 0 ],
            [ RationalField() | 1, 0, 0, -2, 0, 0, 1, 0, 0, -1, 0, 0, -1, 0, 0, 
            2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 3, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, -3, 0, 0, -3, 0, 0, -3, 0, 0, 0, 0, 0,
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, 3, 0, 0, -3, 0, 0, 0, 0, 0, -3, 0, 0, 
            -6, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 2, 0, 0, 5, 0, 0, -4, 0, 0, -2, 0, 0, 7, 0, 0, 
            -2, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 8, 0, 0, 
            7, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 3, 0, 0, -3, 0, 0, 3, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 12, 0, 0, -9, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 
            9, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -1, 0, 0, 5, 0, 0, -1, 0, 0, 4, 0, 0, -5, 0, 0, 
            4, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 21, 0, 0, -11, 0, 0, 11, 0, 0, 0, 0, 0, -1, 0, 
            0, 10, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -9, 0, 0, 7, 0, 0, 8, 0, 0, -9, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 30, 0, 0, 8, 0, 0, -8, 0, 0, 0, 0, 0, 16, 0, 0, 
            8, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 1, 0, 0, 5, 0, 0, 3, 0, 0, 5, 0, 0, 4, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 12, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, -5, 0, 0, 
            -4, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, -3, 0, 0, 3, 0, 0, -3, 0, 0, 
            0, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 6, 0, 0, -6, 0, 0, 6, 0, 0, 0, 0, 0, -3, 0, 0, 
            3, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 0, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | -3, 0, 0, 1, 0, 0, 2, 0, 0, -3, 0, 0, -1, 0, 0, 
            1, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 4, 0, 0, 2,
            0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
            0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 3, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 1, 0, 0, 
            -1, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(27)) |
        [ CyclotomicField(27) |
            [ RationalField() | 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
            0, 0 ],
            [ RationalField() | 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3, 0, 0, 
            -3, 0, 0 ]
        ],
        [ CyclotomicField(27) |
            [ RationalField() | 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0 ],
            [ RationalField() | 9, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -7, 0, 0, 
            -8, 0, 0 ]
        ]
    ]
}
;
E7_ELTS9 := 
{ PowerSequence(PowerSequence(CyclotomicField(9))) |
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, -4, 4, 0, -8, -4 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 1, -1, 0, -4, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, -12, 12, 0, -6, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, -30, 30, 0, -15, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -3, 3, 0, 0, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -3, 3, 0, 0, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, -6, 6, 0, -6, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, -8, 8, 0, -7, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 6, -6, 0, -9, -15 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 6, -6, 0, -9, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 3, -3, 0, 0, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -3, 3, 0, -3, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 15, -15, 0, 9, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, -9, 9, 0, 6, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, -4, 4, 0, -5, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 4, -4, 0, 8, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -1, 1, 0, 16, 17 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 46, 10, -10, 0, -16, -26 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 8, -8, 0, 4, -4 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 4, -4, 0, 5, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, -1, 1, 0, 1, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -2, 2, 0, -4, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, -6, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, 3, -3, 0, -9, -12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, -10, 10, 0, -5, 5 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, -14, 14, 0, -4, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 6, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 1, -1, 0, 8, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 2, -2, 0, 1, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 2, -2, 0, 16, 14 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 10, -10, 0, 32, 22 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, 6, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 3, -3, 0, 6, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, 9, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, 10, -10, 0, 8, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -9, 9, 0, 0, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, -8, 8, 0, -10, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -3, 3, 0, 3, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 6, -6, 0, -6, -12 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 11, -15, 15, 0, -9, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, -26, 26, 0, -10, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, -9, 9, 0, -9, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 16, -16, 0, 17, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -3, 3, 0, 6, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 0, 0, 0, -15, -15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, -12, 12, 0, -12, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 67, -32, 32, 0, -31, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 9, -9, 0, 9, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 10, -10, 0, 17, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, -4, 4, 0, -2, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -8, 8, 0, -4, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -13, 0, 0, 0, -6, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 1, -1, 0, 14, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -1, 1, 0, -2, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 3, -3, 0, 3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, -16, 16, 0, -14, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, -32, 32, 0, -22, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -4, 4, 0, -2, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -5, 5, 0, -1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -4, 4, 0, 7, 11 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 10, -10, 0, -13, -23 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 6, -6, 0, -6, -12 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 6, -6, 0, -15, -21 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -9, 9, 0, 6, 15 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, -6, 6, 0, -15, -9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 6, -6, 0, 3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -3, 3, 0, 3, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, -3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, -3, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 3, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 3, -3, 0, 0, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -3, 3, 0, 3, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -3, 3, 0, -6, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 6, -6, 0, 6, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, 9, -9, 0, 12, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 3, -3, 0, 3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -3, 3, 0, 0, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -27, 27, 0, -27, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 79, 0, 0, 0, 27, 27 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 2, -2, 0, 4, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 4, -4, 0, 8, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 9, -9, 0, 0, -9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, -9, 9, 0, -9, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -21, 21, 0, -21, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 7, -7, 0, 35, 28 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -1, 1, 0, -8, -7 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 7, -7, 0, 8, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -6, 6, 0, 9, 15 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 1, -1, 0, -19, -20 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 9, -9, 0, 0, -9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, -17, 17, 0, -1, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -13, -6, 6, 0, 0, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 13, -13, 0, -1, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, -6, 6, 0, -6, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 4, -4, 0, 5, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -3, 3, 0, -6, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 6, -6, 0, 3, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -7, 7, 0, 1, 8 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 1, -1, 0, -7, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -3, 3, 0, -6, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 6, -6, 0, 12, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, -6, 6, 0, 0, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, -12, 12, 0, -3, 9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -3, 3, 0, 6, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, 7, -7, 0, -10, -17 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 9, -9, 0, 9, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, -2, 2, 0, 8, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, -9, -9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 10, -10, 0, 2, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 12, -12, 0, 0, -12 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 67, 31, -31, 0, -1, -32 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, -3, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 3, -3, 0, -3, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -1, 1, 0, 1, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, -1, 1, 0, -2, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 4, -4, 0, 2, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -9, 9, 0, -6, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, -8, 8, 0, 2, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 6, -6, 0, 0, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 7, -7, 0, -1, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, 9, -9, 0, 3, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, -15, 15, 0, 0, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 8, -8, 0, 10, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 16, -16, 0, 23, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0, 3, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, -4, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 2, -2, 0, 1, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, -1, 1, 0, 4, 5 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 4, -4, 0, -4, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -1, 1, 0, -2, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, -12, 12, 0, -6, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, -21, 21, 0, -6, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, -9, -9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 7, -7, 0, -10, -17 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -15, 15, 0, -6, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, -15, 15, 0, -6, 9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -7, 7, 0, -11, -4 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 13, -13, 0, 23, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 5, -5, 0, 10, 5 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 10, -10, 0, 14, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 3, -3, 0, 3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 4, -4, 0, 5, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 6, -6, 0, 3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -12, 12, 0, -6, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 27, -27, 0, 0, -27 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 79, -27, 27, 0, -27, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 3, -3, 0, 3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -5, 5, 0, -4, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -9, 9, 0, -15, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 19, -19, 0, 20, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 15, -15, 0, 6, -9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, -20, 20, 0, -1, 19 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 11, 6, -6, 0, 15, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 16, -16, 0, 26, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, -9, 9, 0, 0, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, -17, 17, 0, -7, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, -3, 3, 0, 0, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -5, 5, 0, -1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 6, -6, 0, -3, -9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, -2, 2, 0, -10, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 2, -2, 0, -8, -10 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, 7, -7, 0, -16, -23 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -3, 3, 0, 0, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, -3, -3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 9, -9, 0, 15, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 9, -9, 0, 15, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 6, -6, 0, 0, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, -5, 5, 0, -1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 0, 0, 0, 21, 21 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 28, -28, 0, -7, -35 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0, 6, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 1, -1, 0, -4, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -3, 3, 0, -3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, 0, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -1, 1, 0, 1, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, -6, 6, 0, -9, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, 10, -10, 0, 17, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, 17, -17, 0, 1, -16 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 46, -26, 26, 0, -10, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -7, 7, 0, -5, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 13, -13, 0, 8, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 27, 27 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 79, 27, -27, 0, 0, -27 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 3, -3, 0, 3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 3, -3, 0, 3, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -6, 6, 0, -9, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 15, -15, 0, 15, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 3, -3, 0, 0, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, -5, 5, 0, -1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, 11, -11, 0, 4, -7 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, -23, 23, 0, -10, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 8, -8, 0, 7, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, -8, 8, 0, -1, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -3, 3, 0, 0, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, -2, 2, 0, -1, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -13, 6, -6, 0, 6, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, -14, 14, 0, -13, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 32, 0, 0, 0, 12, 12 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 67, 1, -1, 0, 32, 31 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 0, 0, 0, -6, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 1, -1, 0, -13, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, -4, 4, 0, 4, 8 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, -5, 5, 0, -1, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 0, 0, 0, -3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 1, -1, 0, -4, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -16, 16, 0, -17, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 46, 16, -16, 0, 26, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -3, 3, 0, 12, 15 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 28, 15, -15, 0, -15, -30 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 11, 9, -9, 0, -6, -15 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 10, -10, 0, -16, -26 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -6, 6, 0, -15, -9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 31, 15, -15, 0, 9, -6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -9, 9, 0, -9, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 0, 0, 0, 9, 9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 0, 0, 0, 3, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, -3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 3, -3, 0, 3, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, -3, 3, 0, -3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 4, -4, 0, 5, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 6, -6, 0, 12, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 15, -15, 0, 30, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, -6, 6, 0, -3, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, -6, 6, 0, -3, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 0, 0, 0, -3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 1, -1, 0, 5, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 6, -6, 0, 12, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, 15, -15, 0, 21, 6 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, 15, -15, 0, 3, -12 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 28, -30, 30, 0, -15, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 8, 2, -2, 0, -2, -4 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 10, 4, -4, 0, -4, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, 5, -5, 0, -2, -7 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, -8, 8, 0, 5, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 5, 5, -5, 0, -5, -10 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 4, -4, 0, -10, -14 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | -2, 0, 0, 0, 0, 0 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, 6, -6, 0, 6, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, 13, -13, 0, 14, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 21, -21, 0, 0, -21 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, -35, 35, 0, -28, 7 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 6, -6, 0, -6, -12 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 15, -15, 0, -15, -30 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 20, 14, -14, 0, -2, -16 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 49, 22, -22, 0, -10, -32 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, 2, -2, 0, 7, 5 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 19, -5, 5, 0, -13, -8 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, -3, 3, 0, -3, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 0, 0, 0, 3, 3 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 2, -2, 0, 4, 2 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 4, -4, 0, 5, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 0, 0 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 1, 1, -1, 0, 2, 1 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -25, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, 9, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 52, 0, 0, 0, 0, 0 ],
            [ RationalField() | 16, 9, -9, 0, 0, -9 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, -10, 10, 0, -2, 8 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 25, -23, 23, 0, -7, 16 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 2, 2, -2, 0, -2, -4 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 4, 1, -1, 0, -4, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 5, -5, 0, 1, -4 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -8, 8, 0, -4, 4 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -16, 0, 0, 0, 9, 9 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 37, 1, -1, 0, -16, -17 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, -3, 3, 0, 0, 3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 4, -4, 0, -1, -5 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | 14, -6, 6, 0, 0, 6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 22, -14, 14, 0, -1, 13 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 20, 0, 0, 0, 0, 0 ],
            [ RationalField() | -1, 0, 0, 0, -3, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 34, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, 1, -1, 0, -1, -2 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -10, -12, 12, 0, -15, -3 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | -2, 0, 0, 0, 0, 0 ],
            [ RationalField() | 28, 15, -15, 0, 30, 15 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | -7, 0, 0, 0, 0, 0 ],
            [ RationalField() | -7, 9, -9, 0, 3, -6 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 13, -17, 17, 0, -7, 10 ]
        ]
    ],
    [ PowerSequence(CyclotomicField(9)) |
        [ CyclotomicField(9) |
            [ RationalField() | 2, 0, 0, 0, 0, 0 ],
            [ RationalField() | -4, 2, -2, 0, 1, -1 ]
        ],
        [ CyclotomicField(9) |
            [ RationalField() | 7, 0, 0, 0, 0, 0 ],
            [ RationalField() | 7, -2, 2, 0, 2, 4 ]
        ]
    ]
}
;
E8_ELTS9 := 
{ PowerSequence(CyclotomicField(9)) |
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, -1, 1, 0, -5, -4 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, 1, -1, 0, 8, 7 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 134, 1, -1, 0, 56, 55 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 20, 1, -1, 0, -10, -11 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, -1, 1, 0, -2, -1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 56, 28, -28, 0, 56, 28 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 56, -56, 56, 0, -28, 28 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, 5, -5, 0, 4, -1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, 7, -7, 0, -1, -8 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 20, 10, -10, 0, -16, -26 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, 0, 0, 0, -9, -9 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, 2, -2, 0, 1, -1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, -13, 13, 0, 7, 20 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 134, -56, 56, 0, -55, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 17, 9, -9, 0, 18, 9 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, -9, 9, 0, 0, 9 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 32, -24, 24, 0, -3, 21 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, 8, -8, 0, 16, 8 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 8, 1, -1, 0, -1, -2 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 5, 3, -3, 0, -3, -6 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, -7, 7, 0, -20, -13 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 80, -54, 54, 0, -27, 27 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | -1, 1, -1, 0, -1, -2 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, -13, 13, 0, -5, 8 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, -34, 34, 0, -14, 20 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 38, 18, -18, 0, -27, -45 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 56, -43, 43, 0, -11, 32 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, 1, -1, 0, -1, -2 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 56, 32, -32, 0, 43, 11 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 8, -8, 8, 0, -1, 7 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, 20, -20, 0, 34, 14 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 20, -11, 11, 0, -1, 10 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 35, -20, 20, 0, -19, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 80, 27, -27, 0, 54, 27 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, 14, -14, 0, -20, -34 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 17, -18, 18, 0, -9, 9 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 92, -64, 64, 0, -50, 14 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 32, 3, -3, 0, -21, -24 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, -16, 16, 0, -8, 8 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 8, 1, -1, 0, 2, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, -2, 2, 0, -1, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, 9, -9, 0, 9, 0 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 38, 27, -27, 0, 45, 18 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 53, -26, 26, 0, -1, 25 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, 5, -5, 0, -8, -13 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 134, 55, -55, 0, -1, -56 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 8, 1, -1, 0, -7, -8 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, -4, 4, 0, 1, 5 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | -1, 1, -1, 0, 2, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 56, 28, -28, 0, -28, -56 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 35, 1, -1, 0, 20, 19 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, 1, -1, 0, 2, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 17, 9, -9, 0, -9, -18 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 20, 10, -10, 0, 11, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 56, 11, -11, 0, -32, -43 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 35, 19, -19, 0, -1, -20 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 8, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 38, -35, 35, 0, -7, 28 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, 20, -20, 0, 13, -7 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | -1, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, -8, 8, 0, -7, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 5, 3, -3, 0, 6, 3 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, 2, -2, 0, 4, 2 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, 0, 0, 0, 0, 0 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 20, -26, 26, 0, -10, 16 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 32, 21, -21, 0, 24, 3 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 8, -2, 2, 0, -1, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 38, 7, -7, 0, -28, -35 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, -4, 4, 0, -2, 2 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 5, -6, 6, 0, -3, 3 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | -1, -2, 2, 0, -1, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, -1, 1, 0, 1, 2 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 38, -45, 45, 0, -18, 27 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 92, 50, -50, 0, -14, -64 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 38, 28, -28, 0, 35, 7 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 53, 1, -1, 0, -25, -26 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 8, 7, -7, 0, 8, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 2, 2, -2, 0, -2, -4 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 92, 14, -14, 0, 64, 50 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 77, 0, 0, 0, 0, 0 ],
        [ RationalField() | 53, 25, -25, 0, 26, 1 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 5, 0, 0, 0, 0, 0 ],
        [ RationalField() | 80, 27, -27, 0, -27, -54 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 11, 8, -8, 0, 13, 5 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | 14, 0, 0, 0, 0, 0 ],
        [ RationalField() | 29, 8, -8, 0, -8, -16 ]
    ],
    [ CyclotomicField(9) |
        [ RationalField() | -4, 0, 0, 0, 0, 0 ],
        [ RationalField() | 20, 16, -16, 0, 26, 10 ]
    ]
}
;
