"""Assemble the updated Memoir tables (out/tables/6.N.tex, .txt from fg_tables.g) into
tables/{F4,E6,E7,E8}.tex, tables/tables.tex and the per-table part of tables/DIFFERENCES.md.

Usage: python3 assemble_tables.py memoir_numbers.json out/tables <repo>/tables
"""
import sys, json, os, re

nums = json.load(open(sys.argv[1]))
src, dst = sys.argv[2], sys.argv[3]
os.makedirs(dst, exist_ok=True)
TYPES = ['F4', 'E6', 'E7', 'E8']
TITLE = {'F4': '$F_4$', 'E6': '$E_6$', 'E7': '$E_7$', 'E8': '$E_8$'}
MODS = {'F4': '$L(G) = V_{52}$ and $V_{\\min} = V_{26}$', 'E6': '$L(G) = V_{78}$ and $V_{\\min} = V_{27}$',
        'E7': '$L(G) = V_{133}$ and $V_{\\min} = V_{56}$', 'E8': '$L(G) = V_{248}$'}

summ = {}
for x in nums:
    n = x['number']
    tex = os.path.join(src, n + '.tex')
    txt = os.path.join(src, n + '.txt')
    body = open(tex).read() if os.path.exists(tex) else None
    info = open(txt).read().replace('\\\n', '') if os.path.exists(txt) else None
    if body is None:
        k = int(n.split('.')[1])
        body = ('\\setcounter{table}{%d}\n\\begin{longtable}{l}\n\\caption{%s}\\\\\n'
                'Not recomputed: the computation did not finish. See the Memoir.\n\\end{longtable}\n\n'
                % (k - 1, x['caption']))
        info = '%s\t%s\t?\t?\tNOT RECOMPUTED\tcomputation did not finish\n' % (n, x['type'])
    # notes under a table start without a paragraph indent
    body = re.sub(r'\\end\{longtable\}\n(?!\\noindent|\n|$)', r'\\end{longtable}\n\\noindent ', body)
    x['body'], x['info'] = body, info

for ty in TYPES:
    with open(os.path.join(dst, ty + '.tex'), 'w') as f:
        f.write('%% Updated tables for %s (Memoir Chapter 6), generated by tools/fg_tables.g\n' % ty)
        f.write('\\section*{%s: feasible characters on %s}\n\n' % (TITLE[ty], MODS[ty]))
        for x in nums:
            if x['type'] == ty:
                f.write(x['body'])

with open(os.path.join(dst, 'tables.tex'), 'w') as f:
    f.write(r'''\documentclass[10pt]{article}
\usepackage[a4paper,landscape,margin=1.5cm]{geometry}
\usepackage{amsmath,amssymb,longtable,array}
\renewcommand{\thetable}{6.\arabic{table}}
\newcommand{\possprim}{\textbf{P}}
\newcommand{\nongcr}{\textbf{N}}
\newcommand{\newrow}{\textbf{new}}
\newcommand{\Alt}{\mathrm{Alt}}
\setlength{\LTleft}{0pt}
\begin{document}
\title{Feasible characters: updated tables}
\author{Recomputed with \texttt{feasgen.g} (FeasChar repository)}
\date{}
\maketitle
\noindent Table numbers and captions are those of Chapter 6 of A.~J.~Litterick, \emph{On non-generic
finite subgroups of exceptional algebraic groups}, Mem.\ Amer.\ Math.\ Soc.\ 1207 (2018).

\noindent The rows of each table are the feasible characters compatible with the adjoint module, all
end-node Weyl modules and, in characteristic $p$, the irreducible modules $L(\lambda)$ that are
smaller than the corresponding Weyl modules. All element orders are used, and the class
assignment must be compatible with every power map. Only $L(G)$ and $V_{\min}$ are shown, as in
the Memoir.

\noindent Rows are listed up to automorphisms of the character table of $H$ (and, for $F_4$
with $p = 2$, up to the graph automorphism of $F_4$). Columns are labelled by degree, with letters
in the order of the irreducible (Brauer) characters in GAP's character table library. These
labels need not agree with the Memoir's.

\noindent \emph{Provenance.} These tables were computed and typeset by code written by an AI
system (Claude, Anthropic), October 2026, under the direction of the Memoir's author. They are
computational results and have not been independently checked by hand. See the README.

\noindent \possprim, \nongcr: as in the Memoir, carried over from the Memoir row with the same
composition factors. \newrow: not in the Memoir. Differences from the Memoir are listed in
\texttt{DIFFERENCES.md}.
\newpage
''')
    for ty in TYPES:
        f.write('\\input{%s}\n\\newpage\n' % ty)
    f.write('\\end{document}\n')

# per-table differences (Markdown)
lines = []
for ty in TYPES:
    rows = []
    for x in nums:
        if x['type'] != ty:
            continue
        parts = x['info'].strip().split('\t')
        status = parts[4] if len(parts) > 4 else '?'
        rest = parts[5] if len(parts) > 5 else ''
        if status == 'MATCH':
            continue
        cap = re.sub(r'\$|\\nmid|\\neq|\\cdot|\{|\}|\^|_', lambda m: {'\\nmid': '∤', '\\neq': '≠', '\\cdot': '·'}.get(m.group(0), ''), x['caption'])
        cap = re.sub(r'\\possprim|\\nongcr|\\', '', cap)
        cap = re.sub(r'\s+', ' ', cap).strip().replace('|H|', '\\|H\\|')
        if status == 'NOT RECOMPUTED':
            rows.append('| %s | %s | not recomputed: %s |' % (x['number'], cap, rest))
            continue
        m_new = re.search(r'new (\d+)', rest)
        m_rem = re.search(r'removed (\[.*?\]\s*\]|\[\s*\])\s*;', rest)
        desc = []
        rem = m_rem.group(1) if m_rem else '[]'
        for k, why in re.findall(r'\[\s*(\d+),\s*"([^"]*)"\s*\]', rem):
            desc.append('row %s removed (%s)' % (k, why))
        if m_new and int(m_new.group(1)) > 0:
            desc.append('%s new row(s)' % m_new.group(1))
        rows.append('| %s | %s | %s |' % (x['number'], cap, '; '.join(desc) or status))
    lines.append('### %s\n' % ty)
    if rows:
        lines.append('| Table | Group | Difference |\n|---|---|---|')
        lines.extend(rows)
    else:
        lines.append('No differences.')
    lines.append('')
open(os.path.join(dst, 'DIFFERENCES-pertable.md'), 'w').write('\n'.join(lines) + '\n')
# machine-readable tables: tables/<type>.json, and the same data as GAP (tables/<type>.g)
def to_gap(v, ind=''):
    if v is True:
        return 'true'
    if v is False:
        return 'false'
    if v is None:
        return 'fail'
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return '"%s"' % v.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    if isinstance(v, list):
        return '[' + ', '.join(to_gap(x, ind) for x in v) + ']'
    if isinstance(v, dict):
        return 'rec(' + ', '.join('%s := %s' % (k, to_gap(x, ind)) for k, x in v.items()) + ')'
    raise TypeError(type(v))

for ty in TYPES:
    entries = []
    for x in nums:
        if x['type'] != ty:
            continue
        jf = os.path.join(src, x['number'] + '.json')
        if os.path.exists(jf):
            entries.append(json.load(open(jf)))
        else:
            parts = x['info'].strip().split('\t')
            entries.append({'number': x['number'], 'caption': x['caption'], 'type': ty,
                            'status': 'NOT RECOMPUTED', 'reason': parts[5] if len(parts) > 5 else ''})
    with open(os.path.join(dst, ty + '.json'), 'w') as f:
        json.dump({'description': 'Updated feasible-character tables for %s, numbered as in Chapter 6 of '
                   'Mem. AMS 1207. Generated by AI-written code (Claude, Anthropic), October 2026; see the README. '
                   'Check rows with tools/verify_row.g.' % ty, 'tables': entries}, f, indent=1)
    with open(os.path.join(dst, ty + '.g'), 'w') as f:
        f.write('# Updated feasible-character tables for %s (same data as %s.json).\n' % (ty, ty))
        f.write('# Generated by AI-written code (Claude, Anthropic), October 2026; see the README.\n')
        f.write('if not IsBound(FEASCHAR_TABLES) then FEASCHAR_TABLES := rec(); fi;\n')
        f.write('FEASCHAR_TABLES.%s := [\n' % ty)
        f.write(',\n'.join(to_gap(e) for e in entries))
        f.write('];\n')

counts = {}
for x in nums:
    st = x['info'].strip().split('\t')[4] if x['info'] else '?'
    counts[st] = counts.get(st, 0) + 1
print(counts)
