"""Build memoir_index.g: every table of Memoir Chapter 6, with its number (6.N), the GAP name
of the group, the characteristic, and the Memoir's rows (for comparison).

Usage: python3 build_index.py memoir_numbers.json e8tables.json tables_gen.json memoir_index.g
"""
import sys, json, re, io

nums = json.load(open(sys.argv[1]))
e8 = json.load(open(sys.argv[2]))
gen = json.load(open(sys.argv[3]))

E8NAMES = {"PSp4(5)": "S4(5)", "Sp6(2)": "S6(2)", "Omega8^+(2)": "O8+(2)", "^2B2(32)": "Sz(32)",
           "^2B2(8)": "Sz(8)", "^2F4(2)'": "2F4(2)'", "^3D4(2)": "3D4(2)"}

def e8_entry(t):
    cap = t['caption']
    grp = re.sub(r'[\$\{\}_]', '', cap.split('<')[0]).strip().replace('Alt', 'A').replace('\\', '')
    grp = E8NAMES.get(grp, grp)
    pm = re.search(r'p = (\d+)\$?(\s*$|,|\s*or)', cap)
    p = 0 if ('p = 0' in cap or not pm) else int(pm.group(1))
    return {'type': 'E8', 'caption': cap, 'group': grp, 'p': p,
            'mods': [{'name': 'V248', 'labels': t['labels']}],
            'rows': [{'n': r['n'], 'P': r['P'], 'N': r['N'], 'mult': [r['mult']]} for r in t['rows']],
            'perms': t.get('permutations') or '', 'notes': []}

norm = lambda s: re.sub(r'\s+', ' ', s.replace('\\\\', '')).strip()
pool = {'E8': [e8_entry(t) for t in e8]}
for t in gen:
    pool.setdefault(t['type'], []).append(t)
oneliners = {ty: [t for t in pool[ty] if 'irreducible on both' in t['caption']] for ty in pool}
for ty in pool:
    pool[ty] = [t for t in pool[ty] if 'irreducible on both' not in t['caption']]
oneliners['E8'] = [
    {'type': 'E8', 'caption': '$Th < E_8$, $p = 3$ (irreducible on $V_{248}$)', 'group': 'Th', 'p': 3,
     'mods': [{'name': 'V248', 'labels': ['248']}], 'rows': [{'n': 1, 'P': True, 'N': False, 'mult': [[1]]}],
     'perms': '', 'notes': ['hand-entered']},
    {'type': 'E8', 'caption': '$L_4(5) < E_8$, $p = 2$ (irreducible on $V_{248}$)', 'group': 'L4(5)', 'p': 2,
     'mods': [{'name': 'V248', 'labels': ['248']}], 'rows': [{'n': 1, 'P': True, 'N': False, 'mult': [[1]]}],
     'perms': '', 'notes': ['hand-entered']}]

index = []
for x in nums:
    ty = x['type']
    if 'Irreducible on' in x['caption'] or x['caption'] == '(one-line entry)':
        t = oneliners[ty].pop(0)
    else:
        cands = [t for t in pool[ty] if norm(t['caption']) == norm(x['caption'])]
        if not cands:
            raise ValueError('no parsed table for %s %s' % (x['number'], x['caption']))
        t = cands[0]
        pool[ty].remove(t)
    index.append(dict(t, number=x['number']))
left = {ty: len(v) for ty, v in pool.items() if v}
assert not left and not any(oneliners.values()), (left, oneliners)

def g(s):
    return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')
out = ['# Memoir (Mem. AMS 1207) Chapter 6: every table, numbered as in the Memoir.',
       '# Generated by build_index.py from the Memoir LaTeX source.', 'MEMOIR := [];']
for t in index:
    mods = ', '.join('rec(name := %s, labels := [%s])' % (g(m['name']), ', '.join(g(l) for l in m['labels']))
                     for m in t['mods'])
    rows = ',\n    '.join('rec(n := %d, P := %s, N := %s, mult := %s)' % (
        r['n'], str(r['P']).lower(), str(r['N']).lower(), r['mult']) for r in t['rows'])
    out.append('Add(MEMOIR, rec(number := %s, type := %s, caption := %s, group := %s, p := %d,\n'
               '  mods := [%s],\n  perms := %s, notes := [%s],\n  rows := [\n    %s ]));'
               % (g(t['number']), g(t['type']), g(t['caption']), g(t['group']), t['p'], mods,
                  g(t['perms']), ', '.join(g(n) for n in t['notes']), rows))
io.open(sys.argv[4], 'w', encoding='ascii').write('\n'.join(out) + '\n')
print(len(index), 'tables indexed;', index[297]['number'], index[297]['caption'])
