"""Convert F. Luebeck's "Weight multiplicities" pages (WMSmall) into a GAP data file.

Source: http://www.math.rwth-aachen.de/~Frank.Luebeck/chev/WMSmall/
  (E6-50000, E7-100000, E8-500000, F4-30000, G2-700 .html)

Usage: python3 lubeck2gap.py <dir with the .html files> <out.g>

Output: LUBECK.(type) := [ rec(hw, chars, dim, dom := [[wt, mult, orbitlength], ...]) ];
weights in Bourbaki labelling (as on the pages); chars is "all", "2", "not 2, 7", etc.
"""
import sys, re, io, os

PAGES = {"E6": "E6-50000", "E7": "E7-100000", "E8": "E8-500000",
         "F4": "F4-30000", "G2": "G2-700"}

def vec(s):
    return [int(x) for x in s.strip().strip('[]').split(',')]

out = ['# Dominant-weight multiplicities of irreducible modules L(lambda) in characteristic p,',
       '# from F. Luebeck, "Small degree representations ... / Weight multiplicities",',
       '# http://www.math.rwth-aachen.de/~Frank.Luebeck/chev/WMSmall/ (Bourbaki labelling).',
       '# Generated by lubeck2gap.py.  Entries: rec(hw, chars, dim, dom := [[wt, mult, orbitlen], ...]).',
       'LUBECK := rec();']
for typ, page in PAGES.items():
    src = io.open(os.path.join(sys.argv[1], page + '.html'), encoding='latin-1').read()
    blocks = src.split('<strong>Highest weight:</strong>')[1:]
    recs = []
    for b in blocks:
        hw = vec(re.match(r'\s*(\[[^\]]*\])', b).group(1))
        chars = re.search(r'<strong>Characteristic:</strong>\s*(.*?)<br', b).group(1).strip()
        dim = int(re.search(r'<strong>Dimension:</strong>\s*(\d+)', b).group(1))
        tab = b.split('</table>')[0]
        dom = []
        for row in re.findall(r'<tr><td>(\d+)</td><td>(\[[^\]]*\])</td><td>(\d+)</td><td>(\d+)</td></tr>', tab):
            dom.append([vec(row[1]), int(row[2]), int(row[3])])
        if sum(m * o for _, m, o in dom) != dim:
            raise ValueError('dimension check failed: %s %s %s' % (typ, hw, chars))
        recs.append('rec(hw := %s, chars := "%s", dim := %d,\n    dom := %s)' % (hw, chars, dim, dom))
    out.append('LUBECK.%s := [\n  %s ];' % (typ, ',\n  '.join(recs)))
    print(typ, len(recs), 'entries')
io.open(sys.argv[2], 'w', encoding='ascii').write('\n'.join(out) + '\n')
